#!/usr/bin/env python3
"""Lossless source inventory; normalization never changes supplied artifacts."""
import collections
import csv
import hashlib
import json
from pathlib import Path
import re
import tarfile
import yaml

ROOT = Path(__file__).resolve().parents[1]


def digest(data):
    return hashlib.sha256(data).hexdigest()


def write_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")


def load_yaml(text):
    try:
        value = yaml.safe_load(text)
        return {"yaml_status": "empty" if value is None else "parsed",
                "yaml_root": type(value).__name__}, value
    except yaml.YAMLError as e:
        # Unknown/custom tags can be valid YAML (and sometimes valid Ansible).
        # Distinguish construction from actual YAML syntax failures.
        try:
            yaml.compose(text)
            syntax='parsed'
        except yaml.YAMLError:
            syntax='error'
        return {"yaml_status": "load_error", "yaml_syntax_status":syntax,
                "yaml_error_type":type(e).__name__,"yaml_error": str(e)}, None


def main():
    source = ROOT / "data/source"
    rows = list(csv.DictReader((source / "benchmarks.csv").open(newline="")))
    benchmarks = []
    for r in rows:
        b = {"id": f"a{int(r['#']):02}", "paper_id": int(r['#']), "legacy_id": r['P'],
             "natural_language": r['Natural Language'].replace('\\_', '_'),
             "formal_query": r['Formal Query'].replace('\\_', '_'),
             "reference_solution": r['Reference Solution'].replace('\\n', '\n'),
             "provenance": "Aaron-supplied CSV", "review_status": "supplied_not_independently_validated",
             "normalizations": ["decode literal backslash-n in reference", "remove publication backslash before underscore in NL/FQL"]}
        benchmarks.append(b)
    write_json(ROOT / "benchmarks/original.json", benchmarks)
    by_old = {b['legacy_id']: b for b in benchmarks}
    records = {}
    counts = collections.defaultdict(collections.Counter)
    original_diffs = []
    with tarfile.open(source / "astrogator_data.tgz") as tar:
        files = {m.name: m for m in tar.getmembers() if m.isfile()}
        for name, m in sorted(files.items()):
            match = re.fullmatch(r'astrogator_data/([^/]+)/(p\d+[ab]?)/(raw|response|original)(\d+)\.yml', name)
            if not match:
                raise ValueError(f"Unexpected archive member: {name}")
            model, task, kind, sample = match.groups()
            assert task in by_old and int(sample) in range(10)
            content = tar.extractfile(m).read()
            # Only regular whitelisted files, never extract archive paths directly.
            dest = ROOT / "data/corpus" / model / task / f"{kind}{sample}.yml"
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(content)
            key = f"{model}/{task}/{sample}"
            rec = records.setdefault(key, {"sample_id": key, "model": model,
                "task_id": by_old[task]['id'], "legacy_id": task, "sample_index": int(sample),
                "upstream_response_number": int(sample) or 10, "artifacts": {}})
            parsed, obj = load_yaml(content.decode())
            rec['artifacts'][kind] = {"path": str(dest.relative_to(ROOT)), "sha256": digest(content),
                                      "bytes": len(content), **parsed}
            counts[model][kind] += 1
            if kind == 'original':
                processed = tar.extractfile(files[name.replace('/original', '/response')]).read()
                original_diffs.append(content.replace(b'example.com', b'acc240.com') == processed)
    for rec in records.values():
        rec['preprocessing_status'] = 'available' if 'response' in rec['artifacts'] else 'missing_processed'
    ordered = sorted(records.values(), key=lambda r: r['sample_id'])
    (ROOT / 'data/manifest.jsonl').write_text(''.join(json.dumps(r, sort_keys=True) + '\n' for r in ordered))
    summary = {"source_sha256": {p.name: digest(p.read_bytes()) for p in source.iterdir()},
               "benchmark_count": len(benchmarks), "sample_count": len(records),
               "models": dict(counts), "missing_processed": [r['sample_id'] for r in ordered if r['preprocessing_status'] != 'available'],
               "yaml_status_by_kind": {kind: dict(collections.Counter(r['artifacts'][kind]['yaml_status'] for r in ordered if kind in r['artifacts'])) for kind in ['raw', 'response', 'original']},
               "postfix_original_pairs": len(original_diffs),
               "postfix_only_domain_replacement": all(original_diffs)}
    write_json(ROOT / "reports/corpus-audit.json", summary)
    lines = ['# Supplied corpus audit', '', 'Generated by `python3 scripts/audit.py`. YAML parsing is not Ansible syntax or behavioral validation.', '',
             '| Model folder | Raw | Processed | Missing processed |', '|---|---:|---:|---:|']
    for model, c in sorted(counts.items()):
        lines.append(f"| {model} | {c['raw']} | {c['response']} | {c['raw']-c['response']} |")
    lines += ['', f"{len(records)} raw samples; {len(summary['missing_processed'])} missing processed outputs.",
              'Sample index 0 maps to upstream response number 10, not response number 1.', '',
              'All 108 original/processed Postfix pairs differ only by domain substitution.',
              'Preserve all raw attempts in the generation denominator; do not infer correctness from missing processing.',
              'Model folder names are identifiers, not verified model snapshot metadata.', '',
              'The normalized CSV remains a supplied specification, not an independent correctness oracle.']
    (ROOT / 'reports/corpus-audit.md').write_text('\n'.join(lines) + '\n')
    print(json.dumps({k: summary[k] for k in ['benchmark_count','sample_count','yaml_status_by_kind']}))


if __name__ == '__main__':
    main()
