/-!
# CalculusNested: transcription of the nested-state / control fragment of the pinned
# State Calculus interpreter WITH the private patches of the calculus-bytes adapter

Worker: Claude (calculus-resume-2), 2026-09-07. Upstream: `counc009/state_based`, branch
`bash`, commit `190dd8491b258d8a0ee29f79629908540236b332`, `bash-verifier/lib/calculus/`
`interp.ml` + `state.ml` (`ConcreteState`), read together with the two private semantic
patches used by `research/libc-specs/phase5/calculus-bytes/adapter/`:

* `state_concrete_nested.patch` — `set_attr`/`pos_elem`/`neg_elem` rebuild the enclosing
  state on `Nested` paths (the pinned code returned the nested state as the whole state);
* `interp_element_path.patch` — `Element (b, e, a)` APPENDS the hop `(e, a)` to the path of
  `b`, so paths are read outermost-first, which is how every walker in `state.ml` and
  `Value.string_of_value` read them (the pinned producer prepended).

Also transcribed: the v2 adapter's builtin semantics for integers (63-bit carrier with
trapping overflow, truncating division, `Range` assertions) and the interpreter cases
`Pass, Seq, Assign, Action, Add (QualAttr/QualPosE/QualNegE), Get, Contains, Cond, While,
TryCatch, TryFinally, Raise, Return`. NOT transcribed: `Match`, `ForEach`, `ForElem`,
`Localize`, `Yield`, the randomized state, `RangeList`, and state references used as element
KEYS (element arguments here are data values).

Update 2026-09-08 (calculus-correspondence-9, `Byte-list builtins` below): the eleven
`uninterp_table` byte-list/schedule-list primitives (`length, take, drop, slice, append,
single, empty, head_or, tail, min, max` — `calculus-bytes/adapter/bytes_builtin.ml`) are now
transcribed too, so byte-bearing programs (`read_block`/`write_block`/`relay`/... in
`byte_relay_exec.sc`) no longer stop at a `parse_rejected`/`action-not-found` boundary. Lists
are represented WITHOUT a `Left`/`Right` sum tag (`Val` still has only `lit`/`pair`, unedited):
nil is `.lit .unit`, cons is `.pair hd tl` — isomorphic to, but a different Lean-side encoding
than, the OCaml `Left (Literal Unit) | Right (Pair (hd, tl))`; see `Val.asIntList?`/
`Val.ofIntList`. This is still empirical transcription, not extraction: `funcDef`'s new cases
are DEFINED to match `bytes_builtin.ml`'s `func_def`, the same status every other `funcDef`
case already has.

**Trust boundary.** Nothing here is extracted from or checked against the OCaml source by a
machine. The transcription is compared empirically: `NestedFixtures.lean` (generated by
`calculus-bytes/make_lean_fixtures.py` from the lowered S-expressions the OCaml driver
printed and hashed) is executed by `interp` below and its JSON is compared with the OCaml
driver's output by `calculus-bytes/compare_lean_v2.py`. The theorems below are about this
transcription only; they are not theorems about the OCaml program.
-/

namespace CalculusNested

inductive Lit where
  | unit
  | bool (b : Bool)
  | int (n : Int)
  | str (s : String)
  deriving DecidableEq, Repr

/-- Data values (OCaml `Value.t` without `SRef`, `Left/Right`, `Struct`). -/
inductive Val where
  | lit (l : Lit)
  | pair (a b : Val)
  deriving DecidableEq, Repr

/-- State paths (OCaml `Value.s`), read OUTERMOST-FIRST: `nested n v rest` is element
    `n(v)` of the current state, then `rest` inside it. -/
inductive Path where
  | here
  | nested (name : String) (arg : Val) (rest : Path)
  deriving DecidableEq, Repr

/-- Append a hop at the inner end of a path (the patched `Element` case). -/
def Path.snoc : Path → String → Val → Path
  | .here, n, v => .nested n v .here
  | .nested m w rest, n, v => .nested m w (rest.snoc n v)

/-- Runtime values: data or a state reference (`SRef`). -/
inductive RVal where
  | v (x : Val)
  | sref (p : Path)
  -- A pair with at least one `sref` component (e.g. `(pair elementRef (pair off n))`, a real
  -- `byte_relay_exec.sc` pattern: `write_block`'s single argument bundles the target element
  -- reference with two plain ints), added calculus-correspondence-9. A pair of two `v`s still
  -- goes through `Val.pair` exactly as before (see `evalExpr`'s `.pair` case) — `rpair` is
  -- purely additive, for the shape `Val` cannot express (it has no reference case).
  | rpair (a b : RVal)
  deriving DecidableEq, Repr

inductive Func where
  | add | sub | mul | div | mod | lt | le | gt | ge | eq | ne | neg | lnot | fst | snd
  | excTag (t : String)
  | range (lo hi : Int)
  -- Byte-list/schedule-list primitives (`calculus-bytes/adapter/bytes_builtin.ml`'s
  -- `uninterp_table`), added calculus-correspondence-9: see the module docstring's
  -- 2026-09-08 update.
  | length | take | drop | slice | append | single | empty | headOr | tail | min | max
  -- `RangeList` (calculus-correspondence-10): the v2 lowering's declared-`list::<u8>`-sink
  -- assertion, the list counterpart of `range`. Discovered missing when the CORRECTLY
  -- versioned adapter build (see the docstring's 2026-09-08(b) update) turned out to emit
  -- `range-list:lo:hi` around every real byte-list sink, e.g. `write_block`'s `req`.
  | rangeList (lo hi : Int)
  deriving DecidableEq, Repr

inductive Expr where
  | lit (l : Lit)
  | var (x : String)
  | pair (a b : Expr)
  | fn (f : Func) (e : Expr)
  | elem (base : Expr) (name : String) (arg : Expr)
  -- `DecidableEq` added calculus-correspondence-13 (additive; needed so `decide` can
  -- kernel-check that a real exported token list parses to a stated `Stmt`/`Expr`).
  deriving Repr, DecidableEq

inductive Stmt (Act : Type) where
  | pass
  | seq (a b : Stmt Act)
  | action (v : String) (a : Act) (e : Expr)
  | assign (v : String) (e : Expr)
  | setAttr (base : Expr) (attr : String) (e : Expr)
  | addElem (base : Expr) (name : String) (e : Expr)
  | removeElem (base : Expr) (name : String) (e : Expr)
  | get (v : String) (base : Expr) (attr : String)
  | contains (base : Expr) (name : String) (e : Expr) (t f : Stmt Act)
  | cond (c : Expr) (t e : Stmt Act)
  | while (c : Expr) (body : Stmt Act)
  | tryCatch (body : Stmt Act) (v : String) (handler : Stmt Act)
  | tryFinally (body fin : Stmt Act)
  | raise (e : Expr)
  | ret (e : Expr)
  deriving Repr, DecidableEq

/-! ## Association lists (OCaml `Map`s; only lookup / add / remove are used) -/

def lookup {α β : Type} [DecidableEq α] : List (α × β) → α → Option β
  | [], _ => none
  | (k, x) :: rest, a => if k = a then some x else lookup rest a

def assocSet {α β : Type} [DecidableEq α] : List (α × β) → α → β → List (α × β)
  | [], a, y => [(a, y)]
  | (k, x) :: rest, a, y => if k = a then (k, y) :: rest else (k, x) :: assocSet rest a y

def assocRemove {α β : Type} [DecidableEq α] : List (α × β) → α → List (α × β)
  | [], _ => []
  | (k, x) :: rest, a => if k = a then assocRemove rest a else (k, x) :: assocRemove rest a

theorem lookup_assocSet_same {α β : Type} [DecidableEq α] (l : List (α × β)) (a : α) (y : β) :
    lookup (assocSet l a y) a = some y := by
  induction l with
  | nil => simp [assocSet, lookup]
  | cons kx rest ih =>
    obtain ⟨k, x⟩ := kx
    by_cases h : k = a
    · subst h; simp [assocSet, lookup]
    · simp [assocSet, lookup, h, ih]

theorem lookup_assocSet_other {α β : Type} [DecidableEq α] (l : List (α × β)) (a b : α) (y : β)
    (h : b ≠ a) : lookup (assocSet l a y) b = lookup l b := by
  induction l with
  | nil => simp [assocSet, lookup, Ne.symm h]
  | cons kx rest ih =>
    obtain ⟨k, x⟩ := kx
    by_cases hk : k = a
    · subst hk; simp [assocSet, lookup, Ne.symm h]
    · simp [assocSet, lookup, hk, ih]

theorem lookup_assocRemove_same {α β : Type} [DecidableEq α] (l : List (α × β)) (a : α) :
    lookup (assocRemove l a) a = none := by
  induction l with
  | nil => simp [assocRemove, lookup]
  | cons kx rest ih =>
    obtain ⟨k, x⟩ := kx
    by_cases h : k = a
    · subst h; simp [assocRemove, ih]
    · simp [assocRemove, lookup, h, ih]

theorem lookup_assocRemove_other {α β : Type} [DecidableEq α] (l : List (α × β)) (a b : α)
    (h : b ≠ a) : lookup (assocRemove l a) b = lookup l b := by
  induction l with
  | nil => simp [assocRemove, lookup]
  | cons kx rest ih =>
    obtain ⟨k, x⟩ := kx
    by_cases hk : k = a
    · subst hk; simp [assocRemove, lookup, Ne.symm h, ih]
    · simp [assocRemove, lookup, hk, ih]

/-! ## The concrete state tree (OCaml `ConcreteState.t`) and the PATCHED walkers -/

inductive St where
  | mk (attrs : List (String × Val)) (elems : List ((String × Val) × St))

def St.attrs : St → List (String × Val) | .mk a _ => a
def St.elems : St → List ((String × Val) × St) | .mk _ e => e
def St.empty : St := .mk [] []

/-- Constructor-restricted unfolding of `St.mk`'s projections: unlike `St.attrs`/`St.elems`
    (which would also delta-unfold an abstract state and hide it from a `lookup st.elems _`
    hypothesis), this only fires on a literal `St.mk`, which is all `simp` needs to reduce
    the freshly-built states `setAttrAt`/`addElemAt`/`removeElemAt` return. -/
@[simp] theorem St.mk_attrs (a : List (String × Val)) (e : List ((String × Val) × St)) :
    (St.mk a e).attrs = a := rfl
@[simp] theorem St.mk_elems (a : List (String × Val)) (e : List ((String × Val) × St)) :
    (St.mk a e).elems = e := rfl

/-- `get_attr` (unchanged upstream): descend outermost-first, then read the attribute. -/
def getAttrAt : Path → St → String → Option Val
  | .here, st, a => lookup st.attrs a
  | .nested n v rest, st, a =>
    match lookup st.elems (n, v) with
    | none => none
    | some sub => getAttrAt rest sub a

/-- `set_attr` WITH `state_concrete_nested.patch`: the enclosing state is rebuilt. -/
def setAttrAt : Path → St → String → Val → Option St
  | .here, st, a, x => some (.mk (assocSet st.attrs a x) st.elems)
  | .nested n v rest, st, a, x =>
    match lookup st.elems (n, v) with
    | none => none
    | some sub =>
      match setAttrAt rest sub a x with
      | none => none
      | some sub' => some (.mk st.attrs (assocSet st.elems (n, v) sub'))

/-- `pos_elem` WITH the patch (`add_if_absent` at the end of the path). -/
def addElemAt : Path → St → String → Val → Option St
  | .here, st, n, v =>
    some (.mk st.attrs (match lookup st.elems (n, v) with
                        | some _ => st.elems
                        | none => assocSet st.elems (n, v) St.empty))
  | .nested m w rest, st, n, v =>
    match lookup st.elems (m, w) with
    | none => none
    | some sub =>
      match addElemAt rest sub n v with
      | none => none
      | some sub' => some (.mk st.attrs (assocSet st.elems (m, w) sub'))

/-- `neg_elem` WITH the patch. -/
def removeElemAt : Path → St → String → Val → Option St
  | .here, st, n, v => some (.mk st.attrs (assocRemove st.elems (n, v)))
  | .nested m w rest, st, n, v =>
    match lookup st.elems (m, w) with
    | none => none
    | some sub =>
      match removeElemAt rest sub n v with
      | none => none
      | some sub' => some (.mk st.attrs (assocSet st.elems (m, w) sub'))

/-- `check_elem` (unchanged upstream): a missing intermediate element reads as absent. -/
def hasElemAt : Path → St → String → Val → Bool
  | .here, st, n, v => (lookup st.elems (n, v)).isSome
  | .nested m w rest, st, n, v =>
    match lookup st.elems (m, w) with
    | none => false
    | some sub => hasElemAt rest sub n v

/-! ## Frame theorems for the patched mutators

These are the properties the deep-nesting fixture `nested_state.sc` checks by execution
against the patched OCaml (parent and sibling preservation); here they hold for every path,
attribute and state of the transcription. -/

theorem setAttrAt_same : ∀ (p : Path) (st st' : St) (a : String) (x : Val),
    setAttrAt p st a x = some st' → getAttrAt p st' a = some x := by
  intro p
  induction p with
  | here =>
    intro st st' a x h
    simp only [setAttrAt, Option.some.injEq] at h
    subst h
    simp [getAttrAt, St.attrs, lookup_assocSet_same]
  | nested n v rest ih =>
    intro st st' a x h
    simp only [setAttrAt] at h
    split at h
    · cases h
    · rename_i sub hsub
      split at h
      · cases h
      · rename_i sub' hsub'
        simp only [Option.some.injEq] at h
        subst h
        simp [getAttrAt, St.elems, lookup_assocSet_same, ih sub sub' a x hsub']

/-- Writing attribute `a` at path `p` changes no other (path, attribute) pair: the parent's
    attributes, sibling elements and every unrelated subtree are preserved. -/
theorem setAttrAt_frame : ∀ (p : Path) (st st' : St) (a : String) (x : Val),
    setAttrAt p st a x = some st' →
    ∀ (q : Path) (b : String), (q ≠ p ∨ b ≠ a) → getAttrAt q st' b = getAttrAt q st b := by
  intro p
  induction p with
  | here =>
    intro st st' a x h q b hne
    simp only [setAttrAt, Option.some.injEq] at h
    subst h
    cases q with
    | here =>
      have hb : b ≠ a := by
        rcases hne with h1 | h1
        · exact absurd rfl h1
        · exact h1
      simp [getAttrAt, St.attrs, lookup_assocSet_other _ _ _ _ hb]
    | nested m w rest => simp [getAttrAt, St.elems]
  | nested n v rest ih =>
    intro st st' a x h q b hne
    simp only [setAttrAt] at h
    split at h
    · cases h
    · rename_i sub hsub
      split at h
      · cases h
      · rename_i sub' hsub'
        simp only [Option.some.injEq] at h
        subst h
        cases q with
        | here => simp [getAttrAt, St.attrs]
        | nested m w rest' =>
          by_cases hk : (m, w) = (n, v)
          · obtain ⟨rfl, rfl⟩ := Prod.mk.inj hk
            have hr : rest' ≠ rest ∨ b ≠ a := by
              rcases hne with h1 | h1
              · left; intro he; exact h1 (by rw [he])
              · right; exact h1
            simp [getAttrAt, lookup_assocSet_same, hsub, ih sub sub' a x hsub' rest' b hr]
          · simp [getAttrAt, St.elems, lookup_assocSet_other _ _ _ _ hk]

theorem getAttrAt_empty (q : Path) (b : String) : getAttrAt q St.empty b = none := by
  cases q <;> simp [getAttrAt, St.empty, St.attrs, St.elems, lookup]

/-- Touching an element never changes any attribute anywhere (a fresh element is empty;
    an existing one is kept with its attributes: `add_if_absent`). -/
theorem addElemAt_attrs : ∀ (p : Path) (st st' : St) (n : String) (v : Val),
    addElemAt p st n v = some st' →
    ∀ (q : Path) (b : String), getAttrAt q st' b = getAttrAt q st b := by
  intro p
  induction p with
  | here =>
    intro st st' n v h q b
    cases hlk : lookup st.elems (n, v) with
    | some existing =>
      simp only [addElemAt, hlk, Option.some.injEq] at h
      subst h
      cases q with
      | here => simp [getAttrAt, St.attrs]
      | nested m w rest => simp [getAttrAt, St.elems]
    | none =>
      simp only [addElemAt, hlk, Option.some.injEq] at h
      subst h
      cases q with
      | here => simp [getAttrAt, St.attrs]
      | nested m w rest =>
        by_cases hk : (m, w) = (n, v)
        · obtain ⟨rfl, rfl⟩ := Prod.mk.inj hk
          simp [getAttrAt, lookup_assocSet_same, hlk, getAttrAt_empty]
        · simp [getAttrAt, St.elems, lookup_assocSet_other _ _ _ _ hk]
  | nested m0 w0 rest ih =>
    intro st st' n v h q b
    simp only [addElemAt] at h
    split at h
    · cases h
    · rename_i sub hsub
      split at h
      · cases h
      · rename_i sub' hsub'
        simp only [Option.some.injEq] at h
        subst h
        cases q with
        | here => simp [getAttrAt, St.attrs]
        | nested m w rest' =>
          by_cases hk : (m, w) = (m0, w0)
          · obtain ⟨rfl, rfl⟩ := Prod.mk.inj hk
            simp [getAttrAt, lookup_assocSet_same, hsub, ih sub sub' n v hsub' rest' b]
          · simp [getAttrAt, St.elems, lookup_assocSet_other _ _ _ _ hk]

/-- Clearing an element at the root keeps the root attributes and every sibling element. -/
theorem removeElemAt_here_frame (st st' : St) (n : String) (v : Val)
    (h : removeElemAt .here st n v = some st') :
    st'.attrs = st.attrs ∧ ∀ (m : String) (w : Val), (m, w) ≠ (n, v) →
      lookup st'.elems (m, w) = lookup st.elems (m, w) := by
  simp only [removeElemAt, Option.some.injEq] at h
  subst h
  refine ⟨rfl, ?_⟩
  intro m w hk
  simp [St.elems, lookup_assocRemove_other _ _ _ hk]

/-! ## Builtins (adapter v2 integer semantics) and expression evaluation -/

def minInt : Int := -(2 ^ 62)
def maxInt : Int := 2 ^ 62 - 1

/-- carrier check: the OCaml 63-bit int; results outside it trap (`None`). -/
def checked (n : Int) : Option Val :=
  if minInt ≤ n ∧ n ≤ maxInt then some (.lit (.int n)) else none

/-! ## Byte-list encoding (`calculus-bytes/adapter/bytes_builtin.ml`'s `Defs.of_list`/`as_list`/
`as_ints`/`as_bytes`), added calculus-correspondence-9

No new `Val` constructor: nil is `.lit .unit`, cons is `.pair (.lit (.int hd)) tl` — the same
values the rest of this file already builds, just under a fixed shape convention. This cannot
collide with a genuine argument pair `(a, b)` where `b` is a bare int literal (e.g. `Pair(off,
n)`): a real list's tail is always ITSELF `.lit .unit` or a `.pair`, never a bare `.lit (.int _)`
as the second component, so `asIntList?` correctly returns `none` on such a pair (see
`asIntList?_ofIntList` below for the positive direction; the shapes are disjoint on inspection
of the two definitions, so no separate disjointness lemma is needed for anything the parser or
interpreter does with them). -/

def Val.ofIntList : List Int → Val
  | [] => .lit .unit
  | hd :: tl => .pair (.lit (.int hd)) (Val.ofIntList tl)

def Val.asIntList? : Val → Option (List Int)
  | .lit .unit => some []
  | .pair (.lit (.int hd)) tl => (Val.asIntList? tl).map (hd :: ·)
  | _ => none

/-- General round trip: every `List Int`, not just the ones exercised by a fixture. -/
theorem Val.asIntList?_ofIntList : ∀ xs : List Int, Val.asIntList? (Val.ofIntList xs) = some xs
  | [] => rfl
  | hd :: tl => by simp [Val.ofIntList, Val.asIntList?, Val.asIntList?_ofIntList tl]

/-- Byte lists (`Defs.as_bytes`): every element additionally in `[0, 255]`. -/
def Val.asByteList? (v : Val) : Option (List Int) :=
  match Val.asIntList? v with
  | some xs => if xs.all (fun b => decide (0 ≤ b ∧ b ≤ 255)) then some xs else none
  | none => none

def funcDef : Func → Val → Option Val
  | .add, .pair (.lit (.int a)) (.lit (.int b)) => checked (a + b)
  | .sub, .pair (.lit (.int a)) (.lit (.int b)) => checked (a - b)
  | .mul, .pair (.lit (.int a)) (.lit (.int b)) => checked (a * b)
  | .div, .pair (.lit (.int a)) (.lit (.int b)) => if b = 0 then none else checked (Int.tdiv a b)
  | .mod, .pair (.lit (.int a)) (.lit (.int b)) => if b = 0 then none else some (.lit (.int (Int.tmod a b)))
  | .lt, .pair (.lit (.int a)) (.lit (.int b)) => some (.lit (.bool (decide (a < b))))
  | .le, .pair (.lit (.int a)) (.lit (.int b)) => some (.lit (.bool (decide (a ≤ b))))
  | .gt, .pair (.lit (.int a)) (.lit (.int b)) => some (.lit (.bool (decide (b < a))))
  | .ge, .pair (.lit (.int a)) (.lit (.int b)) => some (.lit (.bool (decide (b ≤ a))))
  | .eq, .pair (.lit x) (.lit y) => some (.lit (.bool (decide (x = y))))
  | .ne, .pair (.lit x) (.lit y) => some (.lit (.bool (decide (x ≠ y))))
  | .neg, .lit (.int a) => checked (-a)
  | .lnot, .lit (.bool b) => some (.lit (.bool (!b)))
  | .fst, .pair a _ => some a
  | .snd, .pair _ b => some b
  | .excTag t, .pair (.lit (.str s)) _ => some (.lit (.bool (decide (s = t))))
  | .range lo hi, .lit (.int n) => if lo ≤ n ∧ n ≤ hi then some (.lit (.int n)) else none
  | .rangeList lo hi, v =>
    match Val.asIntList? v with
    | some xs => if xs.all (fun i => decide (lo ≤ i ∧ i ≤ hi)) then some v else none
    | none => none
  | .length, v => (Val.asIntList? v).map (fun xs => .lit (.int xs.length))
  | .empty, .lit .unit => some (Val.ofIntList [])
  | .single, .lit (.int b) => if 0 ≤ b ∧ b ≤ 255 then some (Val.ofIntList [b]) else none
  | .append, .pair a b =>
    match Val.asByteList? a, Val.asByteList? b with
    | some xs, some ys => some (Val.ofIntList (xs ++ ys))
    | _, _ => none
  | .take, .pair a (.lit (.int n)) =>
    match Val.asByteList? a with
    | some xs => if 0 ≤ n ∧ n ≤ (xs.length : Int) then some (Val.ofIntList (xs.take n.toNat)) else none
    | none => none
  | .drop, .pair a (.lit (.int n)) =>
    match Val.asByteList? a with
    | some xs => if 0 ≤ n ∧ n ≤ (xs.length : Int) then some (Val.ofIntList (xs.drop n.toNat)) else none
    | none => none
  | .slice, .pair a (.pair (.lit (.int off)) (.lit (.int n))) =>
    match Val.asByteList? a with
    | some xs =>
      if 0 ≤ off ∧ off ≤ n ∧ n ≤ (xs.length : Int)
      then some (Val.ofIntList ((xs.drop off.toNat).take (n - off).toNat)) else none
    | none => none
  | .headOr, .pair a (.lit (.int d)) =>
    match Val.asIntList? a with
    | some [] => some (.lit (.int d))
    | some (x :: _) => some (.lit (.int x))
    | none => none
  | .tail, v => (Val.asIntList? v).map (fun xs => Val.ofIntList xs.tail)
  | .min, .pair (.lit (.int a)) (.lit (.int b)) => some (.lit (.int (min a b)))
  | .max, .pair (.lit (.int a)) (.lit (.int b)) => some (.lit (.int (max a b)))
  | _, _ => none

abbrev Env := List (String × RVal)

def evalExpr (env : Env) : Expr → Option RVal
  | .lit l => some (.v (.lit l))
  | .var x => lookup env x
  | .pair a b =>
    match evalExpr env a, evalExpr env b with
    | some (.v a), some (.v b) => some (.v (.pair a b))
    | some ra, some rb => some (.rpair ra rb)
    | _, _ => none
  -- `fst`/`snd` of an `rpair` (calculus-correspondence-9) are plain projections, resolved
  -- before `funcDef` (which only knows about `Val`, not `RVal`); `fst`/`snd` of a `Val.pair`
  -- are unaffected, still routed through `funcDef` exactly as before.
  | .fn .fst e =>
    match evalExpr env e with
    | some (.rpair a _) => some a
    | some (.v x) => (funcDef .fst x).map RVal.v
    | _ => none
  | .fn .snd e =>
    match evalExpr env e with
    | some (.rpair _ b) => some b
    | some (.v x) => (funcDef .snd x).map RVal.v
    | _ => none
  | .fn f e =>
    match evalExpr env e with
    | some (.v x) => (funcDef f x).map RVal.v
    | _ => none
  | .elem base n arg =>
    match evalExpr env base, evalExpr env arg with
    | some (.sref p), some (.v a) => some (.sref (p.snoc n a))
    | _, _ => none

/-- General correspondence for `RVal.rpair` (calculus-correspondence-10): `fst`/`snd` of
    `(pair ea eb)` recover exactly `ea`'s/`eb`'s own evaluation, WHATEVER shape it is (plain
    data, a state reference, or itself another `rpair`) — not just measured on the 20-case
    `relay` corpus. This is the property that makes `write_block`'s
    `(assign b (fst ι)) ... (assign n (snd (snd ι)))` chain over the compound argument
    `(pair elementRef (pair off n))` correct in general, for any expressions `ea`/`eb`, not only
    the specific ones `byte_relay_exec.sc` happens to use. -/
theorem evalExpr_fst_pair (env : Env) (ea eb : Expr)
    (ha : (evalExpr env ea).isSome) (hb : (evalExpr env eb).isSome) :
    evalExpr env (.fn .fst (.pair ea eb)) = evalExpr env ea := by
  obtain ⟨ra, hra⟩ := Option.isSome_iff_exists.mp ha
  obtain ⟨rb, hrb⟩ := Option.isSome_iff_exists.mp hb
  simp only [evalExpr, hra, hrb]
  cases ra <;> cases rb <;> simp [funcDef]

theorem evalExpr_snd_pair (env : Env) (ea eb : Expr)
    (ha : (evalExpr env ea).isSome) (hb : (evalExpr env eb).isSome) :
    evalExpr env (.fn .snd (.pair ea eb)) = evalExpr env eb := by
  obtain ⟨ra, hra⟩ := Option.isSome_iff_exists.mp ha
  obtain ⟨rb, hrb⟩ := Option.isSome_iff_exists.mp hb
  simp only [evalExpr, hra, hrb]
  cases ra <;> cases rb <;> simp [funcDef]

/-- More general than `evalExpr_fst_pair`/`_snd_pair` above (calculus-correspondence-11): those
    are about the specific expression shape `.fn .fst (.pair ea eb)`; these are about `.fn .fst e`
    for ANY expression `e` (in particular a bare variable, e.g. `ι`) that HAPPENS to evaluate to
    an `rpair` — which is what `write_block`'s `(fst ι)` actually needs, since `ι` is a variable,
    not syntactically a `.pair`. `evalExpr_fst_pair`/`_snd_pair` are corollaries of these plus
    `evalExpr`'s own `.pair` equation, kept as separate theorems rather than removed (preserving
    the accepted statement, not just its consequence). -/
theorem evalExpr_fst_of_rpair (env : Env) (e : Expr) (a b : RVal)
    (h : evalExpr env e = some (.rpair a b)) :
    evalExpr env (.fn .fst e) = some a := by
  simp [evalExpr, h]

theorem evalExpr_snd_of_rpair (env : Env) (e : Expr) (a b : RVal)
    (h : evalExpr env e = some (.rpair a b)) :
    evalExpr env (.fn .snd e) = some b := by
  simp [evalExpr, h]

inductive Res where
  | continue (env : Env) (st : St)
  | raise (v : Val) (env : Env) (st : St)
  | ret (v : Val) (env : Env) (st : St)
  | failure

def initEnv : Env := [("σ", .sref .here)]
def calleeEnv (arg : RVal) : Env := [("ι", arg), ("σ", .sref .here)]

/-- Transcription of `interp`; `fuel` is consumed at every step (the OCaml recursion is
    unbounded through `Action` and `While`). -/
def interp {Act : Type} (actDef : Act → Stmt Act) : Nat → Stmt Act → Env → St → Res
  | 0, _, _, _ => .failure
  | fuel + 1, s, env, st =>
    match s with
    | .pass => .continue env st
    | .seq a b =>
      match interp actDef fuel a env st with
      | .continue env st => interp actDef fuel b env st
      | r => r
    | .raise e =>
      match evalExpr env e with
      | some (.v x) => .raise x env st
      | _ => .failure
    | .ret e =>
      match evalExpr env e with
      | some x => .ret (match x with | .v x => x | .sref _ => .lit .unit | .rpair _ _ => .lit .unit) env st
      | none => .failure
    | .assign v e =>
      match evalExpr env e with
      | some x => .continue (assocSet env v x) st
      | none => .failure
    | .action v a e =>
      match evalExpr env e with
      | none => .failure
      | some arg =>
        match interp actDef fuel (actDef a) (calleeEnv arg) st with
        | .ret res _ st => .continue (assocSet env v (.v res)) st
        | .raise x _ st => .raise x env st
        | _ => .failure
    | .setAttr base attr e =>
      match evalExpr env base, evalExpr env e with
      | some (.sref p), some (.v x) =>
        match setAttrAt p st attr x with
        | some st => .continue env st
        | none => .failure
      | _, _ => .failure
    | .addElem base n e =>
      match evalExpr env base, evalExpr env e with
      | some (.sref p), some (.v x) =>
        match addElemAt p st n x with
        | some st => .continue env st
        | none => .failure
      | _, _ => .failure
    | .removeElem base n e =>
      match evalExpr env base, evalExpr env e with
      | some (.sref p), some (.v x) =>
        match removeElemAt p st n x with
        | some st => .continue env st
        | none => .failure
      | _, _ => .failure
    | .get v base attr =>
      match evalExpr env base with
      | some (.sref p) =>
        match getAttrAt p st attr with
        | some x => .continue (assocSet env v (.v x)) st
        | none => .failure
      | _ => .failure
    | .contains base n e t f =>
      match evalExpr env base, evalExpr env e with
      | some (.sref p), some (.v x) =>
        if hasElemAt p st n x then interp actDef fuel t env st else interp actDef fuel f env st
      | _, _ => .failure
    | .cond c t e =>
      match evalExpr env c with
      | some (.v (.lit (.bool true))) => interp actDef fuel t env st
      | some (.v (.lit (.bool false))) => interp actDef fuel e env st
      | _ => .failure
    | .while c body =>
      match evalExpr env c with
      | some (.v (.lit (.bool false))) => .continue env st
      | some (.v (.lit (.bool true))) => interp actDef fuel (.seq body (.while c body)) env st
      | _ => .failure
    | .tryCatch body v handler =>
      match interp actDef fuel body env st with
      | .raise x env st => interp actDef fuel handler (assocSet env v (.v x)) st
      | r => r
    | .tryFinally body fin =>
      match interp actDef fuel body env st with
      | .continue env st => interp actDef fuel fin env st
      | .raise x env st =>
        match interp actDef fuel fin env st with
        | .continue env st => .raise x env st
        | r => r
      | .ret x env st =>
        match interp actDef fuel fin env st with
        | .continue env st => .ret x env st
        | r => r
      | .failure => .failure

/-! ## The v2 short-circuit lowering pattern, in general

`e1 && e2` is lowered to `p1; t := e1'; if t then (p2; t := e2') else pass` and `e1 || e2` to
`p1; t := e1'; if t then pass else (p2; t := e2')`. Whatever the right operand is (an
effectful action call or a trapping `1 / 0`), it is not evaluated when the left operand
decides. -/

theorem and_skips_rhs {Act : Type} (actDef : Act → Stmt Act) (fuel : Nat) (t : String) (l : Expr)
    (rhs : Stmt Act) (env : Env) (st : St)
    (h : evalExpr env l = some (.v (.lit (.bool false)))) :
    interp actDef (fuel + 3) (.seq (.assign t l) (.cond (.var t) rhs .pass)) env st =
      .continue (assocSet env t (.v (.lit (.bool false)))) st := by
  simp [interp, evalExpr, h, lookup_assocSet_same]

theorem or_skips_rhs {Act : Type} (actDef : Act → Stmt Act) (fuel : Nat) (t : String) (l : Expr)
    (rhs : Stmt Act) (env : Env) (st : St)
    (h : evalExpr env l = some (.v (.lit (.bool true)))) :
    interp actDef (fuel + 3) (.seq (.assign t l) (.cond (.var t) .pass rhs)) env st =
      .continue (assocSet env t (.v (.lit (.bool true)))) st := by
  simp [interp, evalExpr, h, lookup_assocSet_same]

/-! ## The `write_block`-style triple-destructure assignment pattern, in general
(calculus-correspondence-11)

`write_block`'s REAL exported prefix (see `calculus-correspondence/results/export_input__
byte_relay_exec.tsv`'s `write_block` entry) is exactly
`(seq (assign b (fst ι)) (seq (assign off (fst (snd ι))) (seq (assign n (snd (snd ι))) REST)))`
— `ι` is bound (via `calleeEnv`, at the `action` call site) to whatever the caller's argument
expression evaluated to; `relay`'s call site is `(pair b (pair off r))`, which (since `b` is a
state reference) evaluates through the `.rpair` fallback, not the plain-`Val.pair` case. The
theorem below is a GENERAL statement-level simulation: for ANY `ι` binding shaped as a nested
`rpair` (not just the one `relay` happens to construct) and ANY continuation `rest` (not just
`write_block`'s own), running this exact 3-assignment prefix is equivalent to directly binding
`b`/`off`/`n` to the triple's three components and continuing — connecting `evalExpr_fst_of_rpair`/
`_snd_of_rpair` (expression-level) to `interp` (the statement/program-level semantics) the way
the orchestrator asked, not left as expression lemmas alone. -/
theorem write_block_prefix_binds {Act : Type} (actDef : Act → Stmt Act) (fuel : Nat) (env : Env)
    (st : St) (bv ov nv : RVal) (rest : Stmt Act)
    (hι : lookup env "ι" = some (.rpair bv (.rpair ov nv))) :
    interp actDef (fuel + 3)
      (.seq (.assign "b" (.fn .fst (.var "ι")))
       (.seq (.assign "off" (.fn .fst (.fn .snd (.var "ι"))))
        (.seq (.assign "n" (.fn .snd (.fn .snd (.var "ι")))) rest)))
      env st =
    interp actDef fuel rest (assocSet (assocSet (assocSet env "b" bv) "off" ov) "n" nv) st := by
  have h1 : evalExpr env (.var "ι") = some (.rpair bv (.rpair ov nv)) := by
    simp [evalExpr, hι]
  have h2 := evalExpr_fst_of_rpair env (.var "ι") bv (.rpair ov nv) h1
  have hne1 : "ι" ≠ "b" := by decide
  have hne2 : "ι" ≠ "off" := by decide
  have h1' : evalExpr (assocSet env "b" bv) (.var "ι") = some (.rpair bv (.rpair ov nv)) := by
    simp [evalExpr, lookup_assocSet_other _ _ _ _ hne1, hι]
  have h3' := evalExpr_snd_of_rpair (assocSet env "b" bv) (.var "ι") bv (.rpair ov nv) h1'
  have hfst_off : evalExpr (assocSet env "b" bv) (.fn .fst (.fn .snd (.var "ι"))) = some ov :=
    evalExpr_fst_of_rpair (assocSet env "b" bv) (.fn .snd (.var "ι")) ov nv h3'
  simp only [interp, h2, hfst_off]
  have hne3 : "ι" ≠ "n" := by decide
  have h1'' : evalExpr (assocSet (assocSet env "b" bv) "off" ov) (.var "ι")
      = some (.rpair bv (.rpair ov nv)) := by
    simp [evalExpr, lookup_assocSet_other _ _ _ _ hne2,
      lookup_assocSet_other _ _ _ _ hne1, hι]
  have h3'' := evalExpr_snd_of_rpair (assocSet (assocSet env "b" bv) "off" ov) (.var "ι")
    bv (.rpair ov nv) h1''
  have hsnd_n : evalExpr (assocSet (assocSet env "b" bv) "off" ov)
      (.fn .snd (.fn .snd (.var "ι"))) = some nv :=
    evalExpr_snd_of_rpair (assocSet (assocSet env "b" bv) "off" ov)
      (.fn .snd (.var "ι")) ov nv h3''
  cases fuel with
  | zero => simp [interp]
  | succ k => simp only [interp, hsnd_n]

/-! ## Beyond the prefix: the `range:` wrapper and the assert-or-raise pattern
(calculus-correspondence-12)

Re-reading `write_block`'s CURRENT real export (`calculus-correspondence/results/
export_input__byte_relay_exec.tsv`) found that `write_block_prefix_binds` above, while a true
and still-valid statement about the pattern it names, no longer matches the actual exported
code: the real `off`/`n` assignments are wrapped in `range:0:4611686018427387903(...)` (the v2
lowering's declared-int-sink assertion, `Func.range`), not the bare `(fst (snd ι))`/
`(snd (snd ι))` the -11 theorem states. `write_block_prefix_binds` is kept as-is (still true,
still verified, not weakened or deleted) but does not by itself connect to the real function;
`write_block_prefix_binds_ranged` below is the one that does. -/

/-- A `Func.range lo hi` check is a no-op on a value already known to be in range — this is
    exactly the "declared-int-sink" assertion the v2 lowering inserts around every scalar
    argument bound from a caller-supplied pair (see `funcDef`'s `.range` case). -/
theorem evalExpr_range_pass (env : Env) (e : Expr) (n lo hi : Int)
    (h : evalExpr env e = some (.v (.lit (.int n)))) (hlo : lo ≤ n) (hhi : n ≤ hi) :
    evalExpr env (.fn (.range lo hi) e) = some (.v (.lit (.int n))) := by
  simp [evalExpr, h, funcDef, hlo, hhi]

/-- The MAX bound the real v2 lowering uses for every `range:0:MAX` scalar-sink assertion
    (`calculus-bytes/adapter/lower.ml`'s declared-int-sink constant). -/
def rangeMax : Int := 4611686018427387903

/-- The real `write_block` prefix, exactly as currently exported: `off`/`n` are bound through a
    `range:0:rangeMax` check, not bare projections. General over any `fuel`/continuation/binding,
    same as `write_block_prefix_binds`, plus explicit in-range hypotheses on the two int
    components (the assertion's own precondition — if it fails, `interp` returns `.failure`
    rather than continuing, a case this theorem does not (and need not) characterize, since a
    real `ι` failing its own producer's contract is a lowering/type-soundness question, not one
    this statement-level theorem is about). -/
theorem write_block_prefix_binds_ranged {Act : Type} (actDef : Act → Stmt Act) (fuel : Nat)
    (env : Env) (st : St) (bv : RVal) (ovn nvn : Int) (rest : Stmt Act)
    (hι : lookup env "ι" = some (.rpair bv (.rpair (.v (.lit (.int ovn))) (.v (.lit (.int nvn))))))
    (hlo_o : 0 ≤ ovn) (hhi_o : ovn ≤ rangeMax) (hlo_n : 0 ≤ nvn) (hhi_n : nvn ≤ rangeMax) :
    interp actDef (fuel + 3)
      (.seq (.assign "b" (.fn .fst (.var "ι")))
       (.seq (.assign "off" (.fn (.range 0 rangeMax) (.fn .fst (.fn .snd (.var "ι")))))
        (.seq (.assign "n" (.fn (.range 0 rangeMax) (.fn .snd (.fn .snd (.var "ι"))))) rest)))
      env st =
    interp actDef fuel rest
      (assocSet (assocSet (assocSet env "b" bv) "off" (.v (.lit (.int ovn)))) "n"
        (.v (.lit (.int nvn))))
      st := by
  have h1 : evalExpr env (.var "ι")
      = some (.rpair bv (.rpair (.v (.lit (.int ovn))) (.v (.lit (.int nvn))))) := by
    simp [evalExpr, hι]
  have h2 := evalExpr_fst_of_rpair env (.var "ι") bv
    (.rpair (.v (.lit (.int ovn))) (.v (.lit (.int nvn)))) h1
  have hne1 : "ι" ≠ "b" := by decide
  have hne2 : "ι" ≠ "off" := by decide
  have h1' : evalExpr (assocSet env "b" bv) (.var "ι")
      = some (.rpair bv (.rpair (.v (.lit (.int ovn))) (.v (.lit (.int nvn))))) := by
    simp [evalExpr, lookup_assocSet_other _ _ _ _ hne1, hι]
  have h3' := evalExpr_snd_of_rpair (assocSet env "b" bv) (.var "ι") bv
    (.rpair (.v (.lit (.int ovn))) (.v (.lit (.int nvn)))) h1'
  have hfst_off : evalExpr (assocSet env "b" bv) (.fn .fst (.fn .snd (.var "ι")))
      = some (.v (.lit (.int ovn))) :=
    evalExpr_fst_of_rpair (assocSet env "b" bv) (.fn .snd (.var "ι"))
      (.v (.lit (.int ovn))) (.v (.lit (.int nvn))) h3'
  have hfst_off_ranged := evalExpr_range_pass (assocSet env "b" bv)
    (.fn .fst (.fn .snd (.var "ι"))) ovn 0 rangeMax hfst_off hlo_o hhi_o
  simp only [interp, h2, hfst_off_ranged]
  have hne3 : "ι" ≠ "n" := by decide
  have h1'' : evalExpr (assocSet (assocSet env "b" bv) "off" (.v (.lit (.int ovn)))) (.var "ι")
      = some (.rpair bv (.rpair (.v (.lit (.int ovn))) (.v (.lit (.int nvn))))) := by
    simp [evalExpr, lookup_assocSet_other _ _ _ _ hne2,
      lookup_assocSet_other _ _ _ _ hne1, hι]
  have h3'' := evalExpr_snd_of_rpair (assocSet (assocSet env "b" bv) "off" (.v (.lit (.int ovn))))
    (.var "ι") bv (.rpair (.v (.lit (.int ovn))) (.v (.lit (.int nvn)))) h1''
  have hsnd_n : evalExpr (assocSet (assocSet env "b" bv) "off" (.v (.lit (.int ovn))))
      (.fn .snd (.fn .snd (.var "ι"))) = some (.v (.lit (.int nvn))) :=
    evalExpr_snd_of_rpair (assocSet (assocSet env "b" bv) "off" (.v (.lit (.int ovn))))
      (.fn .snd (.var "ι")) (.v (.lit (.int ovn))) (.v (.lit (.int nvn))) h3''
  have hsnd_n_ranged := evalExpr_range_pass
    (assocSet (assocSet env "b" bv) "off" (.v (.lit (.int ovn))))
    (.fn .snd (.fn .snd (.var "ι"))) nvn 0 rangeMax hsnd_n hlo_n hhi_n
  cases fuel with
  | zero => simp [interp]
  | succ k => simp only [interp, hsnd_n_ranged]

/-! ## The `(seq (cond c pass (raise exc)) rest)` assert-or-raise pattern, in general

`write_block`'s body uses this exact shape three times (`off <= n`, `n <= b.len`, `l <= b.cap`,
each guarding an `AssertionFailure` raise). These two lemmas are the reusable building block;
composed with `write_block_prefix_binds_ranged` below, they extend proof coverage from the
3-assignment prefix through the FIRST assertion (`off <= n`), which depends only on `off`/`n`
(both already bound by the prefix) and needs no assumption about `st`'s shape. The second and
third assertions additionally depend on `.get $t9 b len` / `.get $t11 b cap` — real reads of
`st` at `b`'s reference path — so composing them needs a hypothesis characterizing `st` at that
path; NOT attempted this session (see the README's "Exact remaining theorem obligations"). -/

theorem interp_assert_pass {Act : Type} (actDef : Act → Stmt Act) (fuel : Nat) (env : Env)
    (st : St) (c exc : Expr) (rest : Stmt Act)
    (hc : evalExpr env c = some (.v (.lit (.bool true)))) :
    interp actDef (fuel + 3) (.seq (.cond c .pass (.raise exc)) rest) env st =
      interp actDef (fuel + 2) rest env st := by
  simp [interp, hc]

theorem interp_assert_fail {Act : Type} (actDef : Act → Stmt Act) (fuel : Nat) (env : Env)
    (st : St) (c exc : Expr) (rest : Stmt Act) (v : Val)
    (hc : evalExpr env c = some (.v (.lit (.bool false))))
    (he : evalExpr env exc = some (.v v)) :
    interp actDef (fuel + 3) (.seq (.cond c .pass (.raise exc)) rest) env st =
      .raise v env st := by
  simp [interp, hc, he]

/-- Composed coverage: `write_block`'s real prefix (with the `range:` wrapper) followed by its
    first assertion (`off <= n`), general over `fuel`/`rest`/`bv`/`ovn`/`nvn`, for the pass case.
    This is the "beyond the prefix" extension the orchestrator asked for, scoped honestly: it
    reaches the point just before the first `.get` (state read), not `write_block`'s full body. -/
theorem write_block_through_first_assert_pass {Act : Type} (actDef : Act → Stmt Act) (fuel : Nat)
    (env : Env) (st : St) (bv : RVal) (ovn nvn : Int) (rest : Stmt Act)
    (hι : lookup env "ι" = some (.rpair bv (.rpair (.v (.lit (.int ovn))) (.v (.lit (.int nvn))))))
    (hlo_o : 0 ≤ ovn) (hhi_o : ovn ≤ rangeMax) (hlo_n : 0 ≤ nvn) (hhi_n : nvn ≤ rangeMax)
    (hle : ovn ≤ nvn) :
    interp actDef (fuel + 6)
      (.seq (.assign "b" (.fn .fst (.var "ι")))
       (.seq (.assign "off" (.fn (.range 0 rangeMax) (.fn .fst (.fn .snd (.var "ι")))))
        (.seq (.assign "n" (.fn (.range 0 rangeMax) (.fn .snd (.fn .snd (.var "ι")))))
         (.seq (.cond (.fn .le (.pair (.var "off") (.var "n"))) .pass
                (.raise (.pair (.lit (.str "AssertionFailure")) (.lit .unit)))) rest))))
      env st =
    interp actDef (fuel + 2) rest
      (assocSet (assocSet (assocSet env "b" bv) "off" (.v (.lit (.int ovn)))) "n"
        (.v (.lit (.int nvn))))
      st := by
  have hprefix := write_block_prefix_binds_ranged actDef (fuel + 3) env st bv ovn nvn
    (.seq (.cond (.fn .le (.pair (.var "off") (.var "n"))) .pass
      (.raise (.pair (.lit (.str "AssertionFailure")) (.lit .unit)))) rest)
    hι hlo_o hhi_o hlo_n hhi_n
  rw [show fuel + 6 = (fuel + 3) + 3 by omega, hprefix]
  have hne_off_n : "off" ≠ "n" := by decide
  have hc : evalExpr (assocSet (assocSet (assocSet env "b" bv) "off" (.v (.lit (.int ovn)))) "n"
      (.v (.lit (.int nvn)))) (.fn .le (.pair (.var "off") (.var "n")))
      = some (.v (.lit (.bool true))) := by
    simp [evalExpr, lookup_assocSet_same, lookup_assocSet_other _ _ _ _ hne_off_n, funcDef, hle]
  exact interp_assert_pass actDef fuel
    (assocSet (assocSet (assocSet env "b" bv) "off" (.v (.lit (.int ovn)))) "n"
      (.v (.lit (.int nvn)))) st _ _ rest hc

/-! ## `.while`, one iteration at a time (calculus-correspondence-12)

`relay`'s real export (`calculus-correspondence/results/export_input__byte_relay_exec.tsv`) has
TWO nested `.while` loops: an outer `(while true ...)` that only terminates via a `.ret`/`.raise`
inside its body, and an inner `(while (< (pair off r)) ...)` that terminates when `off` reaches
`r`. These two lemmas are exactly `interp`'s own `.while` equation, restated as general
before/after facts (in the same spirit as `and_skips_rhs`/`or_skips_rhs` above) — deliberately
SCOPED to one iteration. They do NOT constitute termination or invariant-preservation reasoning
for either loop: proving `relay` actually reaches a `.ret`/`.raise` (the outer loop) or that
`off` strictly increases toward `r` without overflow (the inner loop) is real, unstarted work —
listed as an open obligation in the README, not attempted here. What these lemmas DO give: a
mechanically-checked, general (not `relay`-specific) statement of what one step of `interp` does
to any `.while`, usable as a building block for that future termination proof without having to
re-derive `interp`'s pattern match by hand each time. -/

theorem interp_while_true {Act : Type} (actDef : Act → Stmt Act) (fuel : Nat) (env : Env)
    (st : St) (c : Expr) (body : Stmt Act)
    (hc : evalExpr env c = some (.v (.lit (.bool true)))) :
    interp actDef (fuel + 1) (.while c body) env st =
      interp actDef fuel (.seq body (.while c body)) env st := by
  simp [interp, hc]

theorem interp_while_false {Act : Type} (actDef : Act → Stmt Act) (fuel : Nat) (env : Env)
    (st : St) (c : Expr) (body : Stmt Act)
    (hc : evalExpr env c = some (.v (.lit (.bool false)))) :
    interp actDef (fuel + 1) (.while c body) env st = .continue env st := by
  simp [interp, hc]

/-! ## JSON rendering for the empirical comparison with the OCaml driver -/

/-- A well-formed int/byte-list value (`Val.asIntList?`) renders as a flat JSON array,
    comparable to `cb_main.ml`'s `attr_json`, instead of the nested `[hd, [hd2, ...]]` shape a
    generic `.pair` walk would give it. -/
partial def Val.render : Val → String
  | .lit .unit => "\"()\""
  | .lit (.bool b) => if b then "true" else "false"
  | .lit (.int n) => toString n
  | .lit (.str s) => "\"" ++ s ++ "\""
  | v@(.pair a b) =>
    match Val.asIntList? v with
    | some xs => "[" ++ ", ".intercalate (xs.map toString) ++ "]"
    | none => "[" ++ a.render ++ ", " ++ b.render ++ "]"

/-- OCaml `V.string_of_value` for the element argument (ints only in these fixtures). -/
def Val.argText : Val → String
  | .lit (.int n) => toString n
  | .lit (.bool b) => toString b
  | .lit .unit => "()"
  | .lit (.str s) => "\"" ++ s ++ "\""
  | .pair a b => "(" ++ a.argText ++ ", " ++ b.argText ++ ")"

partial def St.render : St → String
  | .mk attrs elems =>
    let as := attrs.map fun (k, v) => "\"" ++ k ++ "\": " ++ v.render
    let es := elems.map fun ((n, v), sub) =>
      "{\"element\": \"" ++ n ++ "\", \"arg\": \"" ++ v.argText ++ "\", " ++ sub.render.drop 1
    "{\"attrs\": {" ++ ", ".intercalate as ++ "}, \"elements\": [" ++ ", ".intercalate es ++ "]}"

def renderRes : Res → String
  | .continue env st =>
    let rc := match lookup env "rc" with
      | some (.v (.lit (.int n))) => toString n
      | _ => "null"
    "\"outcome\": \"continue\", \"rc\": " ++ rc ++ ", \"state\": " ++ st.render
  | .raise x _ st => "\"outcome\": \"raise\", \"value\": " ++ x.render ++ ", \"state\": " ++ st.render
  | .ret x _ st => "\"outcome\": \"return\", \"value\": " ++ x.render ++ ", \"state\": " ++ st.render
  | .failure => "\"outcome\": \"failure\""

/-- Run entry `a` exactly as the OCaml driver does: `Action ("rc", a, ())` from `init_env`. -/
def runEntry {Act : Type} (actDef : Act → Stmt Act) (fuel : Nat) (a : Act) (st : St) : Res :=
  interp actDef fuel (.action "rc" a (.lit .unit)) initEnv st

end CalculusNested
