import BufferRelay

#print axioms BufferRelay.ValidReads
#print axioms BufferRelay.ValidWrites
#print axioms BufferRelay.action
#print axioms BufferRelay.drain
#print axioms BufferRelay.readAmount
#print axioms BufferRelay.readAmount_bounds
#print axioms BufferRelay.readAmount_positive
#print axioms BufferRelay.readAmount_valid
#print axioms BufferRelay.fill
#print axioms BufferRelay.loaded
#print axioms BufferRelay.loaded_eq
#print axioms BufferRelay.retry_pointer_load
#print axioms BufferRelay.execute
#print axioms BufferRelay.runDetailed
#print axioms BufferRelay.run
#print axioms BufferRelay.drain_contract
#print axioms BufferRelay.drain_success
#print axioms BufferRelay.drain_failure_pending
#print axioms BufferRelay.execute_contract
#print axioms BufferRelay.run_prefix
#print axioms BufferRelay.run_output_eq_take
#print axioms BufferRelay.run_success_exact
#print axioms BufferRelay.run_status
#print axioms BufferRelay.run_call_bounds
#print axioms BufferRelay.read_request_valid
#print axioms BufferRelay.fill_frame
#print axioms BufferRelay.write_bounds
#print axioms BufferRelay.drain_stop
#print axioms BufferRelay.drain_retry
#print axioms BufferRelay.execute_read_error
#print axioms BufferRelay.execute_eof
#print axioms BufferRelay.execute_write_failure
#print axioms BufferRelay.run_conservation
#print axioms BufferRelay.run_write_failure_residual
#print axioms BufferRelay.Positive
#print axioms BufferRelay.positive_action
#print axioms BufferRelay.drain_positive
#print axioms BufferRelay.execute_positive
#print axioms BufferRelay.run_positive_success
#print axioms BufferRelay.read_matches_phase1
#print axioms BufferRelay.Examples.default_binary
#print axioms BufferRelay.Examples.retry_binary
#print axioms BufferRelay.Examples.zero_after_short
#print axioms BufferRelay.Examples.error_after_short
#print axioms BufferRelay.Examples.read_error_after_drain
#print axioms BufferRelay.Examples.error_at_eof
#print axioms BufferRelay.Examples.short_failure_pending
