(* GENERATED by validate_text.py gen from text_fixtures.json; do not edit. *)
From Coq Require Import List Ascii String ZArith.
Require Import Shell Parse.
Import ListNotations ShellComposition ShellText.
Local Open Scope string_scope.
Local Open Scope Z_scope.

Example accept_0_parse : parse_program ("t") = Some (call "t").
Proof. vm_compute; reflexivity. Qed.
Example accept_0_run : run test_env (call "t") "" = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example accept_1_parse : parse_program ("f") = Some (call "f").
Proof. vm_compute; reflexivity. Qed.
Example accept_1_run : run test_env (call "f") "" = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example accept_2_parse : parse_program ("  t  ") = Some (call "t").
Proof. vm_compute; reflexivity. Qed.
Example accept_2_run : run test_env (call "t") "" = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example accept_3_parse : parse_program ("t;") = Some (call "t").
Proof. vm_compute; reflexivity. Qed.
Example accept_3_run : run test_env (call "t") "" = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example accept_4_parse : parse_program ("t ; f") = Some (seq (call "t") (call "f")).
Proof. vm_compute; reflexivity. Qed.
Example accept_4_run : run test_env (seq (call "t") (call "f")) "" = (1, ("tf")).
Proof. vm_compute; reflexivity. Qed.
Example accept_5_parse : parse_program ("f;t") = Some (seq (call "f") (call "t")).
Proof. vm_compute; reflexivity. Qed.
Example accept_5_run : run test_env (seq (call "f") (call "t")) "" = (0, ("ft")).
Proof. vm_compute; reflexivity. Qed.
Example accept_6_parse : parse_program ("t && u") = Some (and_then (call "t") (call "u")).
Proof. vm_compute; reflexivity. Qed.
Example accept_6_run : run test_env (and_then (call "t") (call "u")) "" = (0, ("tu")).
Proof. vm_compute; reflexivity. Qed.
Example accept_7_parse : parse_program ("f && u") = Some (and_then (call "f") (call "u")).
Proof. vm_compute; reflexivity. Qed.
Example accept_7_run : run test_env (and_then (call "f") (call "u")) "" = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example accept_8_parse : parse_program ("t || u") = Some (or_else (call "t") (call "u")).
Proof. vm_compute; reflexivity. Qed.
Example accept_8_run : run test_env (or_else (call "t") (call "u")) "" = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example accept_9_parse : parse_program ("f || u") = Some (or_else (call "f") (call "u")).
Proof. vm_compute; reflexivity. Qed.
Example accept_9_run : run test_env (or_else (call "f") (call "u")) "" = (0, ("fu")).
Proof. vm_compute; reflexivity. Qed.
Example accept_10_parse : parse_program ("g || f") = Some (or_else (call "g") (call "f")).
Proof. vm_compute; reflexivity. Qed.
Example accept_10_run : run test_env (or_else (call "g") (call "f")) "" = (1, ("gf")).
Proof. vm_compute; reflexivity. Qed.
Example accept_11_parse : parse_program ("t && f || u") = Some (or_else (and_then (call "t") (call "f")) (call "u")).
Proof. vm_compute; reflexivity. Qed.
Example accept_11_run : run test_env (or_else (and_then (call "t") (call "f")) (call "u")) "" = (0, ("tfu")).
Proof. vm_compute; reflexivity. Qed.
Example accept_12_parse : parse_program ("f || t && g") = Some (and_then (or_else (call "f") (call "t")) (call "g")).
Proof. vm_compute; reflexivity. Qed.
Example accept_12_run : run test_env (and_then (or_else (call "f") (call "t")) (call "g")) "" = (2, ("ftg")).
Proof. vm_compute; reflexivity. Qed.
Example accept_13_parse : parse_program ("f && t || g") = Some (or_else (and_then (call "f") (call "t")) (call "g")).
Proof. vm_compute; reflexivity. Qed.
Example accept_13_run : run test_env (or_else (and_then (call "f") (call "t")) (call "g")) "" = (2, ("fg")).
Proof. vm_compute; reflexivity. Qed.
Example accept_14_parse : parse_program ("t || f && g") = Some (and_then (or_else (call "t") (call "f")) (call "g")).
Proof. vm_compute; reflexivity. Qed.
Example accept_14_run : run test_env (and_then (or_else (call "t") (call "f")) (call "g")) "" = (2, ("tg")).
Proof. vm_compute; reflexivity. Qed.
Example accept_15_parse : parse_program ("f ; t && u") = Some (seq (call "f") (and_then (call "t") (call "u"))).
Proof. vm_compute; reflexivity. Qed.
Example accept_15_run : run test_env (seq (call "f") (and_then (call "t") (call "u"))) "" = (0, ("ftu")).
Proof. vm_compute; reflexivity. Qed.
Example accept_16_parse : parse_program ("t && f ; u") = Some (seq (and_then (call "t") (call "f")) (call "u")).
Proof. vm_compute; reflexivity. Qed.
Example accept_16_run : run test_env (seq (and_then (call "t") (call "f")) (call "u")) "" = (0, ("tfu")).
Proof. vm_compute; reflexivity. Qed.
Example accept_17_parse : parse_program ("f && t ; g") = Some (seq (and_then (call "f") (call "t")) (call "g")).
Proof. vm_compute; reflexivity. Qed.
Example accept_17_run : run test_env (seq (and_then (call "f") (call "t")) (call "g")) "" = (2, ("fg")).
Proof. vm_compute; reflexivity. Qed.
Example accept_18_parse : parse_program ("t ; f ; g") = Some (seq (seq (call "t") (call "f")) (call "g")).
Proof. vm_compute; reflexivity. Qed.
Example accept_18_run : run test_env (seq (seq (call "t") (call "f")) (call "g")) "" = (2, ("tfg")).
Proof. vm_compute; reflexivity. Qed.
Example accept_19_parse : parse_program ("f && (t ; g)") = Some (and_then (call "f") (seq (call "t") (call "g"))).
Proof. vm_compute; reflexivity. Qed.
Example accept_19_run : run test_env (and_then (call "f") (seq (call "t") (call "g"))) "" = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example accept_20_parse : parse_program ("t && (f ; u)") = Some (and_then (call "t") (seq (call "f") (call "u"))).
Proof. vm_compute; reflexivity. Qed.
Example accept_20_run : run test_env (and_then (call "t") (seq (call "f") (call "u"))) "" = (0, ("tfu")).
Proof. vm_compute; reflexivity. Qed.
Example accept_21_parse : parse_program ("(t && f) || u") = Some (or_else (and_then (call "t") (call "f")) (call "u")).
Proof. vm_compute; reflexivity. Qed.
Example accept_21_run : run test_env (or_else (and_then (call "t") (call "f")) (call "u")) "" = (0, ("tfu")).
Proof. vm_compute; reflexivity. Qed.
Example accept_22_parse : parse_program ("t && (f || u)") = Some (and_then (call "t") (or_else (call "f") (call "u"))).
Proof. vm_compute; reflexivity. Qed.
Example accept_22_run : run test_env (and_then (call "t") (or_else (call "f") (call "u"))) "" = (0, ("tfu")).
Proof. vm_compute; reflexivity. Qed.
Example accept_23_parse : parse_program ("(f;)") = Some (call "f").
Proof. vm_compute; reflexivity. Qed.
Example accept_23_run : run test_env (call "f") "" = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example accept_24_parse : parse_program ("( f || g ) && t;") = Some (and_then (or_else (call "f") (call "g")) (call "t")).
Proof. vm_compute; reflexivity. Qed.
Example accept_24_run : run test_env (and_then (or_else (call "f") (call "g")) (call "t")) "" = (2, ("fg")).
Proof. vm_compute; reflexivity. Qed.
Example accept_25_parse : parse_program ("t" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "u") = Some (and_then (call "t") (call "u")).
Proof. vm_compute; reflexivity. Qed.
Example accept_25_run : run test_env (and_then (call "t") (call "u")) "" = (0, ("tu")).
Proof. vm_compute; reflexivity. Qed.
Example accept_26_parse : parse_program ("g || (f && t) || u") = Some (or_else (or_else (call "g") (and_then (call "f") (call "t"))) (call "u")).
Proof. vm_compute; reflexivity. Qed.
Example accept_26_run : run test_env (or_else (or_else (call "g") (and_then (call "f") (call "t"))) (call "u")) "" = (0, ("gfu")).
Proof. vm_compute; reflexivity. Qed.
Example accept_27_parse : parse_program ("( (t) )") = Some (call "t").
Proof. vm_compute; reflexivity. Qed.
Example accept_27_run : run test_env (call "t") "" = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example accept_28_parse : parse_program ("( ( f ) ) || u") = Some (or_else (call "f") (call "u")).
Proof. vm_compute; reflexivity. Qed.
Example accept_28_run : run test_env (or_else (call "f") (call "u")) "" = (0, ("fu")).
Proof. vm_compute; reflexivity. Qed.
Example reject_0 : parse_program ("") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_1 : parse_program ("t | u") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_2 : parse_program ("t > x") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_3 : parse_program ("t &") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_4 : parse_program ("t & u") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_5 : parse_program ("t" ++ String (ascii_of_nat 10) "u") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_6 : parse_program ("t ;; u") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_7 : parse_program ("; t") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_8 : parse_program ("t &&") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_9 : parse_program ("&& t") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_10 : parse_program ("t || || u") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_11 : parse_program ("(t") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_12 : parse_program ("t)") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_13 : parse_program ("()") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_14 : parse_program ("t arg") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_15 : parse_program ("echo $x") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_16 : parse_program ("'t'") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_17 : parse_program ("! t") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_18 : parse_program ("if") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_19 : parse_program ("time t") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_20 : parse_program ("t # c") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_21 : parse_program ("{ t; }") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_22 : parse_program ("t;u;" ++ String (ascii_of_nat 195) "" ++ String (ascii_of_nat 169) "") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_23 : parse_program ("1t") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_24 : parse_program ("t=1") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_25 : parse_program ("$(t)") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_26 : parse_program ("((t))") = None.
Proof. vm_compute; reflexivity. Qed.
Example reject_27 : parse_program ("t && ((u))") = None.
Proof. vm_compute; reflexivity. Qed.

(* Every accepted text therefore has a kernel-checked derivation: *)
Example accept_0_derivation : exists toks, lex_string ("t") = Some toks /\ body_derives toks (call "t").
Proof. apply parse_program_sound. vm_compute; reflexivity. Qed.
