(* GENERATED by validate_text.py random --count 200 --seed 1; bash 5.2.21(1)-release is the oracle. *)
From Coq Require Import List Ascii String ZArith.
Require Import Shell Parse.
Import ListNotations ShellComposition ShellText.
Local Open Scope string_scope.
Local Open Scope Z_scope.
Definition observe (text : string) : Z * string :=
  match parse_program text with
  | Some c => run test_env c ""
  | None => (-1, "")
  end.

Example random_0 : observe ("  (" ++ String (ascii_of_nat 9) "t||" ++ String (ascii_of_nat 9) "g;" ++ String (ascii_of_nat 9) ")||  u||( t ||g ;  (  u  &&" ++ String (ascii_of_nat 9) "t)  || g" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "(g ||  t; g" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "t  ;" ++ String (ascii_of_nat 9) "u ) ||  f" ++ String (ascii_of_nat 9) ";  t &&" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) ")  ;" ++ String (ascii_of_nat 9) "f&& u;  (  t )&&  u ;  ") = (0, ("tftu")).
Proof. vm_compute; reflexivity. Qed.
Example random_1 : observe ("" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "&&f ;  ( u" ++ String (ascii_of_nat 9) "&& (" ++ String (ascii_of_nat 9) "u )" ++ String (ascii_of_nat 9) "&&f;  ( u;f ||  u;" ++ String (ascii_of_nat 9) ");" ++ String (ascii_of_nat 9) "( t ;" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "t  ||  t &&  u  ;" ++ String (ascii_of_nat 9) "u||  g)&& ( u  ||  f;  u" ++ String (ascii_of_nat 9) "&&f||g )  &&" ++ String (ascii_of_nat 9) "(u||  f||  t)||t" ++ String (ascii_of_nat 9) ";) && t" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "f  ||  (  t  )" ++ String (ascii_of_nat 9) "||  t") = (0, ("fuufufuttuuuufgttft")).
Proof. vm_compute; reflexivity. Qed.
Example random_2 : observe ("  g  || f &&  (" ++ String (ascii_of_nat 9) "g ;" ++ String (ascii_of_nat 9) "t ||  (t&& t ||f)  ;" ++ String (ascii_of_nat 9) ") &&  (  u  ) ") = (1, ("gf")).
Proof. vm_compute; reflexivity. Qed.
Example random_3 : observe ("  u|| (" ++ String (ascii_of_nat 9) "u;" ++ String (ascii_of_nat 9) ")  ||" ++ String (ascii_of_nat 9) "( u" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "t )" ++ String (ascii_of_nat 9) "") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_4 : observe ("" ++ String (ascii_of_nat 9) "u&&" ++ String (ascii_of_nat 9) "( g &&  g ||  f &&f  )  ||  (" ++ String (ascii_of_nat 9) "g&&" ++ String (ascii_of_nat 9) "( f &&" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "; t||f&&g" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "|| g )") = (2, ("ugfgg")).
Proof. vm_compute; reflexivity. Qed.
Example random_5 : observe ("  f; t ;  (  u  ||" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "&&  t&&  u  ;" ++ String (ascii_of_nat 9) ")  ||(  f" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "( g &&  u" ++ String (ascii_of_nat 9) ";  u ||g" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "f|| f|| g)" ++ String (ascii_of_nat 9) ")  &&" ++ String (ascii_of_nat 9) "g;") = (2, ("ftuutug")).
Proof. vm_compute; reflexivity. Qed.
Example random_6 : observe ("" ++ String (ascii_of_nat 9) "g;" ++ String (ascii_of_nat 9) "( u||  u &&  t  ||(" ++ String (ascii_of_nat 9) "f ||" ++ String (ascii_of_nat 9) "u  ;  u &&" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "; f ; )" ++ String (ascii_of_nat 9) "; ( u" ++ String (ascii_of_nat 9) "||  g && f&& g" ++ String (ascii_of_nat 9) ";u;)" ++ String (ascii_of_nat 9) "||  (" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) ") )" ++ String (ascii_of_nat 9) "") = (0, ("gutufu")).
Proof. vm_compute; reflexivity. Qed.
Example random_7 : observe ("  (f&&( t  ||  u ; t" ++ String (ascii_of_nat 9) "; t" ++ String (ascii_of_nat 9) "|| t" ++ String (ascii_of_nat 9) "||t);" ++ String (ascii_of_nat 9) "( t || g  ;  f &&u  ||f" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "t  ;f))||  (" ++ String (ascii_of_nat 9) "u|| g||f)  || g||u" ++ String (ascii_of_nat 9) "") = (0, ("ftfffu")).
Proof. vm_compute; reflexivity. Qed.
Example random_8 : observe ("" ++ String (ascii_of_nat 9) "g") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_9 : observe ("" ++ String (ascii_of_nat 9) "( f ||" ++ String (ascii_of_nat 9) "f  ;" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "t ;) ;" ++ String (ascii_of_nat 9) "t &&t  ") = (0, ("ffgttt")).
Proof. vm_compute; reflexivity. Qed.
Example random_10 : observe ("(t" ++ String (ascii_of_nat 9) "&&  u" ++ String (ascii_of_nat 9) "&& t" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "g;" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "g &&  g  || f;f  &&" ++ String (ascii_of_nat 9) "f&&  f || u  ; g&&" ++ String (ascii_of_nat 9) "f  ||  f  )" ++ String (ascii_of_nat 9) "&&  ( u" ++ String (ascii_of_nat 9) "&&f &&  g" ++ String (ascii_of_nat 9) "||u)&&(  u  ||  t|| t  ;" ++ String (ascii_of_nat 9) ");u ;  )  ") = (0, ("tutggffugfu")).
Proof. vm_compute; reflexivity. Qed.
Example random_11 : observe (" f||(f &&  f|| f" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "g ;  t&& (" ++ String (ascii_of_nat 9) "g||  f ;" ++ String (ascii_of_nat 9) "t  &&  t  || u&& g  ;  f" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) ")&&  t )" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "(g  ||" ++ String (ascii_of_nat 9) "t)  ") = (1, ("ffftgfttgf")).
Proof. vm_compute; reflexivity. Qed.
Example random_12 : observe ("  f &&f;" ++ String (ascii_of_nat 9) "") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_13 : observe ("f||" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "; u ") = (0, ("ffu")).
Proof. vm_compute; reflexivity. Qed.
Example random_14 : observe (" g&&" ++ String (ascii_of_nat 9) "g") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_15 : observe (" (  f ||" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "g  && ( g" ++ String (ascii_of_nat 9) ")  ; ( t||" ++ String (ascii_of_nat 9) "u; g ;  u )&&" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "t && g" ++ String (ascii_of_nat 9) "&&g) ;( f  || u" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "|| g  || f  &&f  )  ||" ++ String (ascii_of_nat 9) "g ; )" ++ String (ascii_of_nat 9) "") = (2, ("fugtgutgfuufg")).
Proof. vm_compute; reflexivity. Qed.
Example random_16 : observe ("" ++ String (ascii_of_nat 9) "u ||" ++ String (ascii_of_nat 9) "t&&( g &&g || g  && u" ++ String (ascii_of_nat 9) ";  ( f;  t  ||  t|| u;g &&" ++ String (ascii_of_nat 9) "t || f&& g  )" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "t &&t" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "f &&t ") = (1, ("uggftgfttf")).
Proof. vm_compute; reflexivity. Qed.
Example random_17 : observe ("" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "|| (  t||u" ++ String (ascii_of_nat 9) ")&&" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "f  ||" ++ String (ascii_of_nat 9) "t;" ++ String (ascii_of_nat 9) "f  ;f" ++ String (ascii_of_nat 9) "&&( t  ;  t  &&" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "||u  || u)  )  ;  ( (  u" ++ String (ascii_of_nat 9) "||t" ++ String (ascii_of_nat 9) ")  ; )") = (0, ("uftffu")).
Proof. vm_compute; reflexivity. Qed.
Example random_18 : observe ("  f  ") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_19 : observe (" u  ;(u|| u && t" ++ String (ascii_of_nat 9) "; f  || t" ++ String (ascii_of_nat 9) "; )&& t ;u" ++ String (ascii_of_nat 9) "") = (0, ("uutfttu")).
Proof. vm_compute; reflexivity. Qed.
Example random_20 : observe ("  f&& (" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "||t" ++ String (ascii_of_nat 9) "||  ( g" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "g  ;  g  ||  t||" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) ") ;" ++ String (ascii_of_nat 9) "t||t  ||f&&t  ;  ) ;  ") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_21 : observe ("g" ++ String (ascii_of_nat 9) "&& u&& ( u ||  (f" ++ String (ascii_of_nat 9) "&& t" ++ String (ascii_of_nat 9) ";  g||  g  ;" ++ String (ascii_of_nat 9) ")&&  u ;  ) ") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_22 : observe (" g" ++ String (ascii_of_nat 9) "&&  ( f )  ;") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_23 : observe ("t &&u  &&(t" ++ String (ascii_of_nat 9) ";  ( t  ||  t" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "t;  t  )  ||" ++ String (ascii_of_nat 9) "t  ;)" ++ String (ascii_of_nat 9) "; g  || f||  u" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "(u;" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "|| g" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "g  ;  ") = (2, ("tutttgfuug")).
Proof. vm_compute; reflexivity. Qed.
Example random_24 : observe ("g;" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) ";  ") = (1, ("gf")).
Proof. vm_compute; reflexivity. Qed.
Example random_25 : observe (" u" ++ String (ascii_of_nat 9) "||t" ++ String (ascii_of_nat 9) "&& g ") = (2, ("ug")).
Proof. vm_compute; reflexivity. Qed.
Example random_26 : observe ("u  &&" ++ String (ascii_of_nat 9) "f || u||u" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "u;(" ++ String (ascii_of_nat 9) "g ||" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) ")  || f;") = (0, ("ufuugt")).
Proof. vm_compute; reflexivity. Qed.
Example random_27 : observe (" u  ||  t;" ++ String (ascii_of_nat 9) "g  && g" ++ String (ascii_of_nat 9) "; f ") = (1, ("ugf")).
Proof. vm_compute; reflexivity. Qed.
Example random_28 : observe ("" ++ String (ascii_of_nat 9) "u ") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_29 : observe ("" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "g  ;" ++ String (ascii_of_nat 9) "f ; ") = (1, ("ff")).
Proof. vm_compute; reflexivity. Qed.
Example random_30 : observe (" t  ||" ++ String (ascii_of_nat 9) "f  ||  g ;") = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example random_31 : observe ("  t" ++ String (ascii_of_nat 9) "&&  g ") = (2, ("tg")).
Proof. vm_compute; reflexivity. Qed.
Example random_32 : observe ("  g &&" ++ String (ascii_of_nat 9) "f &&f" ++ String (ascii_of_nat 9) "&&  ( ( f ;u ||" ++ String (ascii_of_nat 9) "f  ; u ;) || f ; )" ++ String (ascii_of_nat 9) ";t" ++ String (ascii_of_nat 9) "; (f  &&" ++ String (ascii_of_nat 9) "g && t  &&  u" ++ String (ascii_of_nat 9) ")||" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "") = (0, ("gtfu")).
Proof. vm_compute; reflexivity. Qed.
Example random_33 : observe ("" ++ String (ascii_of_nat 9) "f &&( (  u" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "t&&t" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) ")|| f)" ++ String (ascii_of_nat 9) "&&u;" ++ String (ascii_of_nat 9) "g") = (2, ("fg")).
Proof. vm_compute; reflexivity. Qed.
Example random_34 : observe ("t" ++ String (ascii_of_nat 9) "; g  ||( f);u" ++ String (ascii_of_nat 9) "") = (0, ("tgfu")).
Proof. vm_compute; reflexivity. Qed.
Example random_35 : observe ("u;f" ++ String (ascii_of_nat 9) "||(t" ++ String (ascii_of_nat 9) "||  u && t  &&" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "") = (0, ("ufttu")).
Proof. vm_compute; reflexivity. Qed.
Example random_36 : observe ("" ++ String (ascii_of_nat 9) "f") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_37 : observe ("g&& t" ++ String (ascii_of_nat 9) "; t ") = (0, ("gt")).
Proof. vm_compute; reflexivity. Qed.
Example random_38 : observe ("" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "u ;g&&  g  &&  u  &&g  ;t" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "") = (0, ("ggtu")).
Proof. vm_compute; reflexivity. Qed.
Example random_39 : observe ("  u||t &&" ++ String (ascii_of_nat 9) "(  f;  );" ++ String (ascii_of_nat 9) "f ") = (1, ("uff")).
Proof. vm_compute; reflexivity. Qed.
Example random_40 : observe ("  u  ") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_41 : observe ("t" ++ String (ascii_of_nat 9) "|| (  (u" ++ String (ascii_of_nat 9) "; u  ) &&g )  ||  (  (" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) ";u" ++ String (ascii_of_nat 9) "&& t ;  u  ||  f  ||t)) && (u||g && (" ++ String (ascii_of_nat 9) "t;  u||  f" ++ String (ascii_of_nat 9) ")  ;(g" ++ String (ascii_of_nat 9) "&& t|| u" ++ String (ascii_of_nat 9) ";g" ++ String (ascii_of_nat 9) "&&u" ++ String (ascii_of_nat 9) "||  t &&  g  ) ; (" ++ String (ascii_of_nat 9) "g  );" ++ String (ascii_of_nat 9) ") ; t" ++ String (ascii_of_nat 9) "&&(" ++ String (ascii_of_nat 9) "g  || g  ||  u; f;" ++ String (ascii_of_nat 9) "g) ||  f||  (  ( f" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "g||f  &&f;" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "t;(" ++ String (ascii_of_nat 9) "f  ; g  &&" ++ String (ascii_of_nat 9) "f &&  t ; ) ;u|| ( g" ++ String (ascii_of_nat 9) "; t" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "g  ||  t" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) ") ;" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) ";  g" ++ String (ascii_of_nat 9) "|| u  ") = (0, ("tutugugtggtggufgffftfgugu")).
Proof. vm_compute; reflexivity. Qed.
Example random_42 : observe ("" ++ String (ascii_of_nat 9) "g  ;" ++ String (ascii_of_nat 9) "( t;)") = (0, ("gt")).
Proof. vm_compute; reflexivity. Qed.
Example random_43 : observe ("  (" ++ String (ascii_of_nat 9) "(  g ||" ++ String (ascii_of_nat 9) "t  ||" ++ String (ascii_of_nat 9) "g  && g" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "g  && t  ||" ++ String (ascii_of_nat 9) "t ) ) &&  (g" ++ String (ascii_of_nat 9) "||t ; (" ++ String (ascii_of_nat 9) "g  ||  g;u" ++ String (ascii_of_nat 9) "&&t&& f" ++ String (ascii_of_nat 9) ";  )  ||g &&  (t" ++ String (ascii_of_nat 9) "&&  f||  t  ||g)||  (" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "; g  ||g" ++ String (ascii_of_nat 9) "&&  u" ++ String (ascii_of_nat 9) "|| t  )  )" ++ String (ascii_of_nat 9) "") = (0, ("gtggtgtggutfgtggt")).
Proof. vm_compute; reflexivity. Qed.
Example random_44 : observe ("f" ++ String (ascii_of_nat 9) "") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_45 : observe ("g;") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_46 : observe ("" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "; t ") = (0, ("tt")).
Proof. vm_compute; reflexivity. Qed.
Example random_47 : observe (" (  u" ++ String (ascii_of_nat 9) "&&  t)&&f" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "( u &&  g  )  ") = (2, ("utfug")).
Proof. vm_compute; reflexivity. Qed.
Example random_48 : observe ("  u && g  &&" ++ String (ascii_of_nat 9) "g;  (" ++ String (ascii_of_nat 9) "f ;  )|| g;  (  ( g )  ;  f && g||u )  ") = (0, ("ugfggfu")).
Proof. vm_compute; reflexivity. Qed.
Example random_49 : observe (" g  ||  t ;" ++ String (ascii_of_nat 9) "f&&(" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "||(  u ||" ++ String (ascii_of_nat 9) "g|| g ||f ;  f ||  f;  )  ;  (" ++ String (ascii_of_nat 9) "f ||" ++ String (ascii_of_nat 9) "g ;" ++ String (ascii_of_nat 9) "t ;  t  &&" ++ String (ascii_of_nat 9) "t  &&f  ; )&&  (  g )" ++ String (ascii_of_nat 9) "|| (  g||  g" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "; t" ++ String (ascii_of_nat 9) "&& g" ++ String (ascii_of_nat 9) ") ||f&&  g  ;t || (  t  &&" ++ String (ascii_of_nat 9) "f &&( g&&" ++ String (ascii_of_nat 9) "t|| t" ++ String (ascii_of_nat 9) "; u;" ++ String (ascii_of_nat 9) "f  &&  g ||  u  ||  u) ; );" ++ String (ascii_of_nat 9) "") = (0, ("gtfft")).
Proof. vm_compute; reflexivity. Qed.
Example random_50 : observe ("u  ||u" ++ String (ascii_of_nat 9) "||  f" ++ String (ascii_of_nat 9) "|| f" ++ String (ascii_of_nat 9) "; f  ") = (1, ("uf")).
Proof. vm_compute; reflexivity. Qed.
Example random_51 : observe (" ( g||  g" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "t  )" ++ String (ascii_of_nat 9) "||g") = (0, ("gggt")).
Proof. vm_compute; reflexivity. Qed.
Example random_52 : observe ("" ++ String (ascii_of_nat 9) "g && f" ++ String (ascii_of_nat 9) "; g && u||(  u ; ( u" ++ String (ascii_of_nat 9) "|| t &&" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "; t &&u ; u  &&  t  || g )||" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "|| (" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "f ;" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "|| u ||t )" ++ String (ascii_of_nat 9) ") ") = (0, ("gguuutuut")).
Proof. vm_compute; reflexivity. Qed.
Example random_53 : observe ("  t  &&" ++ String (ascii_of_nat 9) "(f && g" ++ String (ascii_of_nat 9) ")  ;" ++ String (ascii_of_nat 9) "(g &&u; u &&  g)" ++ String (ascii_of_nat 9) "||  (  u && ( f  || u  &&t  && g)" ++ String (ascii_of_nat 9) ") ||" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "||f  ;(g || f) ||  t  ||u&&" ++ String (ascii_of_nat 9) "g;" ++ String (ascii_of_nat 9) "") = (2, ("tfgugufutgtgftg")).
Proof. vm_compute; reflexivity. Qed.
Example random_54 : observe ("  u" ++ String (ascii_of_nat 9) "||(  (  g ||u &&" ++ String (ascii_of_nat 9) "u  && u;  )&&(  g" ++ String (ascii_of_nat 9) "||  u" ++ String (ascii_of_nat 9) "||  g  ||" ++ String (ascii_of_nat 9) "u;  u||t||u ||" ++ String (ascii_of_nat 9) "u )  ;)&& g ") = (2, ("ug")).
Proof. vm_compute; reflexivity. Qed.
Example random_55 : observe ("" ++ String (ascii_of_nat 9) "(  (u" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "g &&f  ||  f; g" ++ String (ascii_of_nat 9) "||g  ;u" ++ String (ascii_of_nat 9) "&& f )  &&t || g  ;" ++ String (ascii_of_nat 9) ") ; t  &&u|| ( g" ++ String (ascii_of_nat 9) "&& (  t &&u  &&  f &&  g;g  )  ||  g;g;" ++ String (ascii_of_nat 9) "); u  ||" ++ String (ascii_of_nat 9) "u") = (0, ("ugfggufgtuu")).
Proof. vm_compute; reflexivity. Qed.
Example random_56 : observe ("" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "&&  g" ++ String (ascii_of_nat 9) "") = (2, ("tg")).
Proof. vm_compute; reflexivity. Qed.
Example random_57 : observe ("g  ") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_58 : observe (" g&& g" ++ String (ascii_of_nat 9) "") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_59 : observe ("" ++ String (ascii_of_nat 9) "u ;  ") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_60 : observe ("" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) ";  f  ; g" ++ String (ascii_of_nat 9) "||  t  ;  ") = (0, ("ufgt")).
Proof. vm_compute; reflexivity. Qed.
Example random_61 : observe ("u  && ( u||" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "t )" ++ String (ascii_of_nat 9) ";  (  u  ;  g&&u" ++ String (ascii_of_nat 9) "||t  ;  f" ++ String (ascii_of_nat 9) ")  )  &&  f ") = (1, ("uuugtf")).
Proof. vm_compute; reflexivity. Qed.
Example random_62 : observe ("g  || f" ++ String (ascii_of_nat 9) "") = (1, ("gf")).
Proof. vm_compute; reflexivity. Qed.
Example random_63 : observe (" g;t|| t" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "") = (1, ("gtf")).
Proof. vm_compute; reflexivity. Qed.
Example random_64 : observe ("g||" ++ String (ascii_of_nat 9) "f&&" ++ String (ascii_of_nat 9) "(  u  ;f&&  (" ++ String (ascii_of_nat 9) "u&&  t" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "&& t ;  u && u" ++ String (ascii_of_nat 9) "&&g" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "g ) ||f || ( g|| u" ++ String (ascii_of_nat 9) ";  u||t&&t  ); g  || u)" ++ String (ascii_of_nat 9) "||  t ") = (0, ("gft")).
Proof. vm_compute; reflexivity. Qed.
Example random_65 : observe (" u" ++ String (ascii_of_nat 9) "") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_66 : observe (" t  || t ;t  ") = (0, ("tt")).
Proof. vm_compute; reflexivity. Qed.
Example random_67 : observe (" g && t ;" ++ String (ascii_of_nat 9) "") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_68 : observe ("  t ;  t ||  f;") = (0, ("tt")).
Proof. vm_compute; reflexivity. Qed.
Example random_69 : observe ("  u" ++ String (ascii_of_nat 9) "&&g;  g &&" ++ String (ascii_of_nat 9) "u ; u  || (" ++ String (ascii_of_nat 9) "f  ;" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "u  &&g") = (2, ("uggug")).
Proof. vm_compute; reflexivity. Qed.
Example random_70 : observe ("u ;  f  &&u  || t|| g" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "t") = (0, ("uftt")).
Proof. vm_compute; reflexivity. Qed.
Example random_71 : observe ("" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "(  u" ++ String (ascii_of_nat 9) "||  t||  f  ||  t)" ++ String (ascii_of_nat 9) "||g" ++ String (ascii_of_nat 9) "&& g  &&  ( t ||" ++ String (ascii_of_nat 9) "f &&  u ;" ++ String (ascii_of_nat 9) "g ;" ++ String (ascii_of_nat 9) "))||" ++ String (ascii_of_nat 9) "g;  f  && u  ;(" ++ String (ascii_of_nat 9) "u;" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "||  t ;u  || u ||(  f  ||  f" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "g  ||" ++ String (ascii_of_nat 9) "u  ))" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "(  (g  )" ++ String (ascii_of_nat 9) ";  t" ++ String (ascii_of_nat 9) "||g" ++ String (ascii_of_nat 9) "||g || (  g )" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "u && f" ++ String (ascii_of_nat 9) ")") = (0, ("uggfuuu")).
Proof. vm_compute; reflexivity. Qed.
Example random_72 : observe ("" ++ String (ascii_of_nat 9) "( f  &&  f  ;  (f ;f  ;" ++ String (ascii_of_nat 9) ")  ||  (  t" ++ String (ascii_of_nat 9) ";  t &&  u ;" ++ String (ascii_of_nat 9) "u  && t" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "g  );" ++ String (ascii_of_nat 9) "g &&g  ") = (2, ("fffttuutgg")).
Proof. vm_compute; reflexivity. Qed.
Example random_73 : observe ("" ++ String (ascii_of_nat 9) "t  && t") = (0, ("tt")).
Proof. vm_compute; reflexivity. Qed.
Example random_74 : observe ("u") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_75 : observe ("f ||  t ;") = (0, ("ft")).
Proof. vm_compute; reflexivity. Qed.
Example random_76 : observe ("t  &&u" ++ String (ascii_of_nat 9) "") = (0, ("tu")).
Proof. vm_compute; reflexivity. Qed.
Example random_77 : observe (" (" ++ String (ascii_of_nat 9) "f  ;  t;" ++ String (ascii_of_nat 9) "u  &&  u  ||  ( t &&  u  ;)" ++ String (ascii_of_nat 9) ")&& t ;  (g&& (" ++ String (ascii_of_nat 9) "t  ||t  &&  f&&" ++ String (ascii_of_nat 9) "u ; t|| u  ;  g&&  g ) ;  u||  t &&  f" ++ String (ascii_of_nat 9) ")  ") = (1, ("ftuutguf")).
Proof. vm_compute; reflexivity. Qed.
Example random_78 : observe (" u|| u" ++ String (ascii_of_nat 9) "") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_79 : observe ("t|| g ") = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example random_80 : observe ("u" ++ String (ascii_of_nat 9) "||  t;" ++ String (ascii_of_nat 9) "g  ;" ++ String (ascii_of_nat 9) "") = (2, ("ug")).
Proof. vm_compute; reflexivity. Qed.
Example random_81 : observe ("  (  t&& g  ;  (" ++ String (ascii_of_nat 9) "g) ; )  ") = (2, ("tgg")).
Proof. vm_compute; reflexivity. Qed.
Example random_82 : observe (" g" ++ String (ascii_of_nat 9) ";( u  &&" ++ String (ascii_of_nat 9) "g  ;u||" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) ";  t) ") = (0, ("gugut")).
Proof. vm_compute; reflexivity. Qed.
Example random_83 : observe ("f&&" ++ String (ascii_of_nat 9) "f  ;  t  ;  u &&  (" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "u||t) )" ++ String (ascii_of_nat 9) ";") = (1, ("ftuf")).
Proof. vm_compute; reflexivity. Qed.
Example random_84 : observe ("" ++ String (ascii_of_nat 9) "( (g" ++ String (ascii_of_nat 9) "||f  ))&&  t  ;  (" ++ String (ascii_of_nat 9) "g  ;t ||t; (" ++ String (ascii_of_nat 9) "g  && g" ++ String (ascii_of_nat 9) "|| t;" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) ";  )" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "t&& (  g&&f && u  )  ;" ++ String (ascii_of_nat 9) "u ") = (0, ("gfgtgtgu")).
Proof. vm_compute; reflexivity. Qed.
Example random_85 : observe ("" ++ String (ascii_of_nat 9) "(  ( t  &&" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "&& t &&g ; (" ++ String (ascii_of_nat 9) "u|| f  ;" ++ String (ascii_of_nat 9) "u&& f ||  u" ++ String (ascii_of_nat 9) "))") = (0, ("tutguufu")).
Proof. vm_compute; reflexivity. Qed.
Example random_86 : observe ("g" ++ String (ascii_of_nat 9) "||t ; g||  f  ; g &&t  || f||  g  ") = (2, ("gtgfgfg")).
Proof. vm_compute; reflexivity. Qed.
Example random_87 : observe ("u  ;" ++ String (ascii_of_nat 9) "f  || f ; ") = (1, ("uff")).
Proof. vm_compute; reflexivity. Qed.
Example random_88 : observe (" (" ++ String (ascii_of_nat 9) "g  &&" ++ String (ascii_of_nat 9) "u; u|| ( g ;" ++ String (ascii_of_nat 9) "g&&f|| g" ++ String (ascii_of_nat 9) "; u|| g  &&" ++ String (ascii_of_nat 9) "g )  ;)  ") = (0, ("gu")).
Proof. vm_compute; reflexivity. Qed.
Example random_89 : observe ("( u  || t ||  g||(" ++ String (ascii_of_nat 9) "u  &&g  ;  f && g&&  f" ++ String (ascii_of_nat 9) ";  g )  )" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "t ||  f  ") = (0, ("ut")).
Proof. vm_compute; reflexivity. Qed.
Example random_90 : observe ("" ++ String (ascii_of_nat 9) "f||" ++ String (ascii_of_nat 9) "u&&f; u  ") = (0, ("fufu")).
Proof. vm_compute; reflexivity. Qed.
Example random_91 : observe (" u" ++ String (ascii_of_nat 9) "&&t&&" ++ String (ascii_of_nat 9) "g") = (2, ("utg")).
Proof. vm_compute; reflexivity. Qed.
Example random_92 : observe ("t  ") = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example random_93 : observe ("u||" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_94 : observe ("  g  ; g&&" ++ String (ascii_of_nat 9) "u ") = (2, ("gg")).
Proof. vm_compute; reflexivity. Qed.
Example random_95 : observe ("  (f  ;  g )  ;  (  (" ++ String (ascii_of_nat 9) "u &&" ++ String (ascii_of_nat 9) "u  ; f ||u&& g  ; t  )" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "t  &&  (" ++ String (ascii_of_nat 9) "t ;" ++ String (ascii_of_nat 9) ") && u)" ++ String (ascii_of_nat 9) "||(" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "&&  (  f  &&f&& u&&t" ++ String (ascii_of_nat 9) ";t" ++ String (ascii_of_nat 9) "&&  f) &&u)  ||u") = (0, ("fguufugttu")).
Proof. vm_compute; reflexivity. Qed.
Example random_96 : observe ("  t||" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "g") = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example random_97 : observe ("" ++ String (ascii_of_nat 9) "f ;" ++ String (ascii_of_nat 9) "f  &&  u" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "f|| f" ++ String (ascii_of_nat 9) ";(  f" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "g )") = (1, ("ffff")).
Proof. vm_compute; reflexivity. Qed.
Example random_98 : observe ("( t||" ++ String (ascii_of_nat 9) "u )  ||  f" ++ String (ascii_of_nat 9) "") = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example random_99 : observe ("  u;" ++ String (ascii_of_nat 9) "u  ;" ++ String (ascii_of_nat 9) "t &&f") = (1, ("uutf")).
Proof. vm_compute; reflexivity. Qed.
Example random_100 : observe (" g ;" ++ String (ascii_of_nat 9) "(  g&&" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "&&t" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "u;  g" ++ String (ascii_of_nat 9) "&& t" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "(  g" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "t&&" ++ String (ascii_of_nat 9) "g ; u" ++ String (ascii_of_nat 9) "||t" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "u  ;)  ||u" ++ String (ascii_of_nat 9) "||  t) || (" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) ");" ++ String (ascii_of_nat 9) "g") = (2, ("gguggtguug")).
Proof. vm_compute; reflexivity. Qed.
Example random_101 : observe ("  g" ++ String (ascii_of_nat 9) "") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_102 : observe ("u ;f  ;" ++ String (ascii_of_nat 9) "u  &&  ( f ;)" ++ String (ascii_of_nat 9) "|| u" ++ String (ascii_of_nat 9) "") = (0, ("ufufu")).
Proof. vm_compute; reflexivity. Qed.
Example random_103 : observe ("t" ++ String (ascii_of_nat 9) ";  u  &&" ++ String (ascii_of_nat 9) "f;  ( ( f;" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) ")  ") = (0, ("tufft")).
Proof. vm_compute; reflexivity. Qed.
Example random_104 : observe ("u && (u) ;" ++ String (ascii_of_nat 9) "") = (0, ("uu")).
Proof. vm_compute; reflexivity. Qed.
Example random_105 : observe ("" ++ String (ascii_of_nat 9) "g ||  t" ++ String (ascii_of_nat 9) "") = (0, ("gt")).
Proof. vm_compute; reflexivity. Qed.
Example random_106 : observe (" u" ++ String (ascii_of_nat 9) "; t ") = (0, ("ut")).
Proof. vm_compute; reflexivity. Qed.
Example random_107 : observe ("  f" ++ String (ascii_of_nat 9) "") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_108 : observe ("g  ; f" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "(g&&  g  || u &&" ++ String (ascii_of_nat 9) "(u" ++ String (ascii_of_nat 9) ");u ) && t" ++ String (ascii_of_nat 9) "") = (1, ("gf")).
Proof. vm_compute; reflexivity. Qed.
Example random_109 : observe (" g" ++ String (ascii_of_nat 9) "|| (u" ++ String (ascii_of_nat 9) ") ; f; u" ++ String (ascii_of_nat 9) "") = (0, ("gufu")).
Proof. vm_compute; reflexivity. Qed.
Example random_110 : observe ("" ++ String (ascii_of_nat 9) "g ||  f ") = (1, ("gf")).
Proof. vm_compute; reflexivity. Qed.
Example random_111 : observe ("  f  &&(" ++ String (ascii_of_nat 9) "f  &&  f" ++ String (ascii_of_nat 9) "|| ( t &&  g" ++ String (ascii_of_nat 9) "||  f" ++ String (ascii_of_nat 9) "||g;f &&u  ||  f ;  t ||  u  &&t ||" ++ String (ascii_of_nat 9) "t);" ++ String (ascii_of_nat 9) "u );") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_112 : observe ("  g&&" ++ String (ascii_of_nat 9) "g;t") = (0, ("gt")).
Proof. vm_compute; reflexivity. Qed.
Example random_113 : observe ("" ++ String (ascii_of_nat 9) "f ") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_114 : observe (" f ") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_115 : observe ("" ++ String (ascii_of_nat 9) "( f&&  u||  u  )  ||" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "&&(f  )" ++ String (ascii_of_nat 9) "") = (1, ("fuf")).
Proof. vm_compute; reflexivity. Qed.
Example random_116 : observe ("t  ||( f" ++ String (ascii_of_nat 9) "&& g ; )") = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example random_117 : observe ("  ( t  || t;" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "||  (  (  t  ||g  ;)" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "&&u  &&" ++ String (ascii_of_nat 9) "u ") = (0, ("tuu")).
Proof. vm_compute; reflexivity. Qed.
Example random_118 : observe ("" ++ String (ascii_of_nat 9) "f||u &&(f||" ++ String (ascii_of_nat 9) "g  ||" ++ String (ascii_of_nat 9) "f  ;" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "; t|| u; ") = (0, ("fufgft")).
Proof. vm_compute; reflexivity. Qed.
Example random_119 : observe ("" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "f ||f  || (  t&&t ;" ++ String (ascii_of_nat 9) "g;" ++ String (ascii_of_nat 9) "( f&& u)||  u)" ++ String (ascii_of_nat 9) "; (  (t&&" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) ")") = (2, ("ffttgfutg")).
Proof. vm_compute; reflexivity. Qed.
Example random_120 : observe ("f" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_121 : observe (" t ||( u" ++ String (ascii_of_nat 9) ")||  u ;  ") = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example random_122 : observe ("  g ; f &&  t  &&" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "&&(" ++ String (ascii_of_nat 9) "t); u && u &&  (" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "( g  ||" ++ String (ascii_of_nat 9) "u  ;)" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "( u  ||g; t" ++ String (ascii_of_nat 9) "&& t" ++ String (ascii_of_nat 9) ";f" ++ String (ascii_of_nat 9) ")  ||(" ++ String (ascii_of_nat 9) "g; f&&" ++ String (ascii_of_nat 9) "t||" ++ String (ascii_of_nat 9) "u||  u;g  ; )  ;  f ||(t" ++ String (ascii_of_nat 9) "&&f|| u  &&" ++ String (ascii_of_nat 9) "t;" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) ";  g" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) ";)" ++ String (ascii_of_nat 9) ";") = (2, ("gfuuggfugftfutgg")).
Proof. vm_compute; reflexivity. Qed.
Example random_123 : observe (" t|| g&&" ++ String (ascii_of_nat 9) "g;(" ++ String (ascii_of_nat 9) "u || t)&&  u" ++ String (ascii_of_nat 9) ";  f &&f;" ++ String (ascii_of_nat 9) "") = (1, ("tguuf")).
Proof. vm_compute; reflexivity. Qed.
Example random_124 : observe (" t &&" ++ String (ascii_of_nat 9) "u||u") = (0, ("tu")).
Proof. vm_compute; reflexivity. Qed.
Example random_125 : observe ("" ++ String (ascii_of_nat 9) "g || g  ||" ++ String (ascii_of_nat 9) "(u&&" ++ String (ascii_of_nat 9) "(u)" ++ String (ascii_of_nat 9) "||f  ||" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "u &&  (  t  && f ;t || t||" ++ String (ascii_of_nat 9) "u  &&" ++ String (ascii_of_nat 9) "g  )&& (" ++ String (ascii_of_nat 9) "t  )" ++ String (ascii_of_nat 9) ")&&(  f  ;" ++ String (ascii_of_nat 9) "t &&" ++ String (ascii_of_nat 9) "g  )") = (2, ("gguuutftg")).
Proof. vm_compute; reflexivity. Qed.
Example random_126 : observe ("" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "||g" ++ String (ascii_of_nat 9) "||u|| f") = (0, ("fgu")).
Proof. vm_compute; reflexivity. Qed.
Example random_127 : observe ("  (t  ||g )" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "g  || g &&" ++ String (ascii_of_nat 9) "t;f;u") = (0, ("tggfu")).
Proof. vm_compute; reflexivity. Qed.
Example random_128 : observe ("f ") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_129 : observe (" u ") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_130 : observe ("" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "&& u  ;  ") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_131 : observe ("f" ++ String (ascii_of_nat 9) "&& t") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_132 : observe ("  (t ; g" ++ String (ascii_of_nat 9) ")  || u ||  (  t" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "( t)  ;" ++ String (ascii_of_nat 9) "g ;(u ||  g  )" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) ")  &&" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "") = (0, ("tgut")).
Proof. vm_compute; reflexivity. Qed.
Example random_133 : observe ("  g  ") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_134 : observe (" f" ++ String (ascii_of_nat 9) "&&  f&&  (  f ||  f ;" ++ String (ascii_of_nat 9) ") ;t ||  t ;" ++ String (ascii_of_nat 9) "(  (  t &&g  && t  )&&  f||u ||" ++ String (ascii_of_nat 9) "f )" ++ String (ascii_of_nat 9) "") = (0, ("fttgu")).
Proof. vm_compute; reflexivity. Qed.
Example random_135 : observe (" f" ++ String (ascii_of_nat 9) "&& f  ") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_136 : observe (" t&&t ||" ++ String (ascii_of_nat 9) "t&& f ;  ") = (1, ("ttf")).
Proof. vm_compute; reflexivity. Qed.
Example random_137 : observe ("  g  && u ") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_138 : observe (" f &&  u" ++ String (ascii_of_nat 9) "") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_139 : observe (" u  ;" ++ String (ascii_of_nat 9) "") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_140 : observe ("" ++ String (ascii_of_nat 9) "f &&(" ++ String (ascii_of_nat 9) "t  ;  (  f  ) ;" ++ String (ascii_of_nat 9) ") &&" ++ String (ascii_of_nat 9) "f  ||t  ") = (0, ("ft")).
Proof. vm_compute; reflexivity. Qed.
Example random_141 : observe ("g ;t||g ") = (0, ("gt")).
Proof. vm_compute; reflexivity. Qed.
Example random_142 : observe ("  u  &&  g  &&" ++ String (ascii_of_nat 9) "( t" ++ String (ascii_of_nat 9) ";)" ++ String (ascii_of_nat 9) ";  ") = (2, ("ug")).
Proof. vm_compute; reflexivity. Qed.
Example random_143 : observe ("" ++ String (ascii_of_nat 9) "(  u  )  ||  u|| t  &&  f ;  f|| u" ++ String (ascii_of_nat 9) "") = (0, ("uffu")).
Proof. vm_compute; reflexivity. Qed.
Example random_144 : observe ("" ++ String (ascii_of_nat 9) "t") = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example random_145 : observe (" t|| g  ") = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example random_146 : observe ("" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "t&&  t  &&" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "&&  g)" ++ String (ascii_of_nat 9) "||( f" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "u )&& f  ;u  &&f" ++ String (ascii_of_nat 9) "||  (" ++ String (ascii_of_nat 9) "u  &&  (u  &&t  ;g" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "g  ||" ++ String (ascii_of_nat 9) "t; f)" ++ String (ascii_of_nat 9) "|| (" ++ String (ascii_of_nat 9) "u  && u" ++ String (ascii_of_nat 9) ";  g" ++ String (ascii_of_nat 9) "||  t" ++ String (ascii_of_nat 9) ") ||" ++ String (ascii_of_nat 9) "(  u" ++ String (ascii_of_nat 9) "||u||g||t ;f ; );f||" ++ String (ascii_of_nat 9) "t  ;" ++ String (ascii_of_nat 9) "f )  &&" ++ String (ascii_of_nat 9) "f  ") = (1, ("tttgfufufuutggtfuugtftf")).
Proof. vm_compute; reflexivity. Qed.
Example random_147 : observe ("  ( f && t&& (  t &&  g;g" ++ String (ascii_of_nat 9) ";u );" ++ String (ascii_of_nat 9) "(t" ++ String (ascii_of_nat 9) ";u)|| f);") = (0, ("ftu")).
Proof. vm_compute; reflexivity. Qed.
Example random_148 : observe (" (  u" ++ String (ascii_of_nat 9) ";u  ||  g" ++ String (ascii_of_nat 9) "; f" ++ String (ascii_of_nat 9) "||( u" ++ String (ascii_of_nat 9) ";u ||" ++ String (ascii_of_nat 9) "u)" ++ String (ascii_of_nat 9) ")  ||  g &&  f  ||  (g ;g  ||u &&  u && (" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "g  &&  u" ++ String (ascii_of_nat 9) "; ))") = (2, ("uufuufgguutg")).
Proof. vm_compute; reflexivity. Qed.
Example random_149 : observe ("  u||  (  g" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "f||  ( g" ++ String (ascii_of_nat 9) "||f; ) ||g )" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "t&&" ++ String (ascii_of_nat 9) "( f&& (" ++ String (ascii_of_nat 9) "g );(  u)" ++ String (ascii_of_nat 9) "&&f ;  u  &&  t ) ") = (0, ("utfufut")).
Proof. vm_compute; reflexivity. Qed.
Example random_150 : observe ("  f&&( f ) && u" ++ String (ascii_of_nat 9) "") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_151 : observe ("" ++ String (ascii_of_nat 9) "( u &&" ++ String (ascii_of_nat 9) "u ) || f|| g" ++ String (ascii_of_nat 9) "&&(" ++ String (ascii_of_nat 9) "( u" ++ String (ascii_of_nat 9) "||t" ++ String (ascii_of_nat 9) ";g" ++ String (ascii_of_nat 9) "; t; ) ||  u  ||" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "f) ; g&& f ") = (2, ("uuugtfg")).
Proof. vm_compute; reflexivity. Qed.
Example random_152 : observe ("(g || ( g; g" ++ String (ascii_of_nat 9) ";t )" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) ";  g;  g|| (  t  ;" ++ String (ascii_of_nat 9) "t||  u" ++ String (ascii_of_nat 9) "; g" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "|| (t || u&&  t )" ++ String (ascii_of_nat 9) "&&t" ++ String (ascii_of_nat 9) "") = (0, ("gggtfggttgttt")).
Proof. vm_compute; reflexivity. Qed.
Example random_153 : observe ("f &&  t &&u ") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_154 : observe ("t&& (" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) ";)" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "u ;)  ") = (0, ("tftu")).
Proof. vm_compute; reflexivity. Qed.
Example random_155 : observe ("  u ") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_156 : observe ("f" ++ String (ascii_of_nat 9) "; f  &&  (  u || f &&" ++ String (ascii_of_nat 9) "(f  ||  u  ||t" ++ String (ascii_of_nat 9) "||  f)&& (" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "&&  g);  t  ||" ++ String (ascii_of_nat 9) "u )" ++ String (ascii_of_nat 9) "; t ") = (0, ("fft")).
Proof. vm_compute; reflexivity. Qed.
Example random_157 : observe ("(  f" ++ String (ascii_of_nat 9) "&&  t;(" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "&&  f  && f  &&" ++ String (ascii_of_nat 9) "f  ; f  ;" ++ String (ascii_of_nat 9) "t &&g  ||t" ++ String (ascii_of_nat 9) ")||u" ++ String (ascii_of_nat 9) ")  ||" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) ";  u&&" ++ String (ascii_of_nat 9) "f &&" ++ String (ascii_of_nat 9) "t || t ") = (0, ("ftfftgtuft")).
Proof. vm_compute; reflexivity. Qed.
Example random_158 : observe ("  (u  ||" ++ String (ascii_of_nat 9) "(  f" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "||  t  ; u" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "||  f" ++ String (ascii_of_nat 9) ") ") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_159 : observe (" u  || f;  f" ++ String (ascii_of_nat 9) "|| f" ++ String (ascii_of_nat 9) "||  u  ") = (0, ("uffu")).
Proof. vm_compute; reflexivity. Qed.
Example random_160 : observe ("  t||" ++ String (ascii_of_nat 9) "u&& f  ;  f  ;  g" ++ String (ascii_of_nat 9) "&&  u  &&" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "") = (2, ("tffg")).
Proof. vm_compute; reflexivity. Qed.
Example random_161 : observe ("  u  ;t ||(  g ||g)  ;(" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "t ;" ++ String (ascii_of_nat 9) "g|| f" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "||( f ||" ++ String (ascii_of_nat 9) "g||t  && t  ;" ++ String (ascii_of_nat 9) "t; u" ++ String (ascii_of_nat 9) "||  g  &&t;)&&g  && (" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "||t ;  u  ||  t ; ) ; f||u" ++ String (ascii_of_nat 9) ";u  ||  u) ||" ++ String (ascii_of_nat 9) "g ") = (0, ("uttgffgtttutgfuu")).
Proof. vm_compute; reflexivity. Qed.
Example random_162 : observe ("" ++ String (ascii_of_nat 9) "( u &&  t|| (" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) ") )" ++ String (ascii_of_nat 9) "; t ; ( u" ++ String (ascii_of_nat 9) "&&  u||  (  f ||  g" ++ String (ascii_of_nat 9) "||g  ; g )  ;( u" ++ String (ascii_of_nat 9) "||t  ;f &&t||  t|| f" ++ String (ascii_of_nat 9) ";  t" ++ String (ascii_of_nat 9) "&&g||f" ++ String (ascii_of_nat 9) "||u" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "u;(" ++ String (ascii_of_nat 9) "t  && g  )  && u" ++ String (ascii_of_nat 9) "|| (  u &&g&&" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "t||g" ++ String (ascii_of_nat 9) "||g" ++ String (ascii_of_nat 9) ";  g" ++ String (ascii_of_nat 9) "&&u  &&" ++ String (ascii_of_nat 9) "u&&  f" ++ String (ascii_of_nat 9) ") )" ++ String (ascii_of_nat 9) ";  ") = (2, ("uttuuufttgfutgugttg")).
Proof. vm_compute; reflexivity. Qed.
Example random_163 : observe ("u  ; t  ") = (0, ("ut")).
Proof. vm_compute; reflexivity. Qed.
Example random_164 : observe ("  t" ++ String (ascii_of_nat 9) "||  ( f" ++ String (ascii_of_nat 9) "|| u  && (u" ++ String (ascii_of_nat 9) "||f;  u" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "f;u  )  && f" ++ String (ascii_of_nat 9) "; f" ++ String (ascii_of_nat 9) "&&  g&& t; g ||" ++ String (ascii_of_nat 9) "g ;" ++ String (ascii_of_nat 9) ") &&(  t || u ||g  ||  u  )") = (0, ("tt")).
Proof. vm_compute; reflexivity. Qed.
Example random_165 : observe ("f ;  (  f||  f  ) ") = (1, ("fff")).
Proof. vm_compute; reflexivity. Qed.
Example random_166 : observe ("f") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_167 : observe ("(g ;" ++ String (ascii_of_nat 9) ")  ") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_168 : observe ("u" ++ String (ascii_of_nat 9) "&& g  ;  g&&  u" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "g&& t||" ++ String (ascii_of_nat 9) "f  ") = (1, ("ugggf")).
Proof. vm_compute; reflexivity. Qed.
Example random_169 : observe ("  f" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "( (f||g; f;t  ||f&&u  &&f ;  )" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "u || (  u&& g || g  ) ;t;  (u  && t ) && g" ++ String (ascii_of_nat 9) ");" ++ String (ascii_of_nat 9) "") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_170 : observe (" f  ;" ++ String (ascii_of_nat 9) "(  (  u ) ||u&&  f" ++ String (ascii_of_nat 9) "||  t" ++ String (ascii_of_nat 9) ";f  ; t" ++ String (ascii_of_nat 9) "||  g)" ++ String (ascii_of_nat 9) "") = (0, ("fuftft")).
Proof. vm_compute; reflexivity. Qed.
Example random_171 : observe ("  t &&t" ++ String (ascii_of_nat 9) ";f  && t" ++ String (ascii_of_nat 9) "") = (1, ("ttf")).
Proof. vm_compute; reflexivity. Qed.
Example random_172 : observe ("" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "|| u" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "(g ||  t &&  g&& f ; )" ++ String (ascii_of_nat 9) "||  ( g" ++ String (ascii_of_nat 9) "&&f" ++ String (ascii_of_nat 9) "&&  f ;u;" ++ String (ascii_of_nat 9) "u) ") = (0, ("fugtgguu")).
Proof. vm_compute; reflexivity. Qed.
Example random_173 : observe (" f&&  t  ;  u" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "") = (0, ("fu")).
Proof. vm_compute; reflexivity. Qed.
Example random_174 : observe ("g  ||  t ;u || t  &&  g&&  f") = (2, ("gtug")).
Proof. vm_compute; reflexivity. Qed.
Example random_175 : observe ("f  ;") = (1, ("f")).
Proof. vm_compute; reflexivity. Qed.
Example random_176 : observe ("g&& t  ;  f" ++ String (ascii_of_nat 9) "&& (  (" ++ String (ascii_of_nat 9) "u&&t ||" ++ String (ascii_of_nat 9) "u &&  u  ; ) &&" ++ String (ascii_of_nat 9) "g; f  ||" ++ String (ascii_of_nat 9) "f||t  && u ; f&& g )" ++ String (ascii_of_nat 9) "") = (1, ("gf")).
Proof. vm_compute; reflexivity. Qed.
Example random_177 : observe ("  (f||" ++ String (ascii_of_nat 9) "(t||" ++ String (ascii_of_nat 9) "u  ) ;  u ;t;" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "|| t  ||g") = (0, ("ftut")).
Proof. vm_compute; reflexivity. Qed.
Example random_178 : observe ("u  || u&&  u" ++ String (ascii_of_nat 9) ";(g" ++ String (ascii_of_nat 9) "|| f  )||(u  ||  u)") = (0, ("uugfu")).
Proof. vm_compute; reflexivity. Qed.
Example random_179 : observe ("  u  ||(u&& u  )&&u && g") = (2, ("uug")).
Proof. vm_compute; reflexivity. Qed.
Example random_180 : observe ("" ++ String (ascii_of_nat 9) "(  f&&" ++ String (ascii_of_nat 9) "(  t ;t;" ++ String (ascii_of_nat 9) "g;)  ; t )" ++ String (ascii_of_nat 9) "&&  t" ++ String (ascii_of_nat 9) "&&(" ++ String (ascii_of_nat 9) "(t&& g  &&  t||  g  ;" ++ String (ascii_of_nat 9) "g;  t && g &&g" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "f;) &&" ++ String (ascii_of_nat 9) "t||(" ++ String (ascii_of_nat 9) "u || u" ++ String (ascii_of_nat 9) ") &&" ++ String (ascii_of_nat 9) "(  g || f  &&" ++ String (ascii_of_nat 9) "u  ; f" ++ String (ascii_of_nat 9) "&&g  ;" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "&& t );  (" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) ")&&" ++ String (ascii_of_nat 9) "( f  ||" ++ String (ascii_of_nat 9) "g  );  t  ||(  g &&  f )" ++ String (ascii_of_nat 9) ")  ;  f  ") = (1, ("ftttgggtgfugffgutgtf")).
Proof. vm_compute; reflexivity. Qed.
Example random_181 : observe ("" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "||u") = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example random_182 : observe (" ( (" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "&& t ) ") = (0, ("tt")).
Proof. vm_compute; reflexivity. Qed.
Example random_183 : observe (" g  ;  u||  t  ;  g ") = (2, ("gug")).
Proof. vm_compute; reflexivity. Qed.
Example random_184 : observe ("  t ;  u|| t &&  ( t" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "||  f)" ++ String (ascii_of_nat 9) "&&(g  ||u  ||  u" ++ String (ascii_of_nat 9) "&& f" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) ") ") = (1, ("tutff")).
Proof. vm_compute; reflexivity. Qed.
Example random_185 : observe ("" ++ String (ascii_of_nat 9) "u  ||( (g && u ||" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) ")  && t;  t &&" ++ String (ascii_of_nat 9) "( g &&f" ++ String (ascii_of_nat 9) "||f ;u" ++ String (ascii_of_nat 9) "&&" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) ") ;( f" ++ String (ascii_of_nat 9) ";  u && g ;)  ||" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "; t && u ||" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "&& (" ++ String (ascii_of_nat 9) "g; t  && f  ;f" ++ String (ascii_of_nat 9) "||(" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "&&  f  );" ++ String (ascii_of_nat 9) ")  ;" ++ String (ascii_of_nat 9) "g&&(" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) ") ") = (2, ("utugtffufg")).
Proof. vm_compute; reflexivity. Qed.
Example random_186 : observe ("( t  || (" ++ String (ascii_of_nat 9) "u ||u;  ) )|| t;" ++ String (ascii_of_nat 9) "u && g ") = (2, ("tug")).
Proof. vm_compute; reflexivity. Qed.
Example random_187 : observe ("" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "g ||  f" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "t&& u" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "") = (0, ("fgftu")).
Proof. vm_compute; reflexivity. Qed.
Example random_188 : observe ("" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "g  ") = (0, ("t")).
Proof. vm_compute; reflexivity. Qed.
Example random_189 : observe ("  t" ++ String (ascii_of_nat 9) "||t  ;  f" ++ String (ascii_of_nat 9) ";(f  &&" ++ String (ascii_of_nat 9) "u" ++ String (ascii_of_nat 9) "||u|| t  ; )") = (0, ("tffu")).
Proof. vm_compute; reflexivity. Qed.
Example random_190 : observe ("" ++ String (ascii_of_nat 9) "t || (u" ++ String (ascii_of_nat 9) ";( u  ||f ) ||" ++ String (ascii_of_nat 9) "(u;u" ++ String (ascii_of_nat 9) "&& g ;  )  ;f  &&  ( g || t" ++ String (ascii_of_nat 9) ")  )" ++ String (ascii_of_nat 9) "; u ;" ++ String (ascii_of_nat 9) "t &&  (  t" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) ")" ++ String (ascii_of_nat 9) "|| f") = (0, ("tutt")).
Proof. vm_compute; reflexivity. Qed.
Example random_191 : observe ("" ++ String (ascii_of_nat 9) "(  t  && t)  ||" ++ String (ascii_of_nat 9) "t &&" ++ String (ascii_of_nat 9) "u  &&u ;" ++ String (ascii_of_nat 9) "f&&" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "g||  g") = (2, ("ttuufgg")).
Proof. vm_compute; reflexivity. Qed.
Example random_192 : observe ("" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) "") = (2, ("g")).
Proof. vm_compute; reflexivity. Qed.
Example random_193 : observe ("u ") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_194 : observe ("u  || (f" ++ String (ascii_of_nat 9) "&&t; t )||" ++ String (ascii_of_nat 9) "(  u|| (  f &&g && t || t" ++ String (ascii_of_nat 9) ")  ;  u&&  (" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "|| u  )" ++ String (ascii_of_nat 9) "&&  t ||g" ++ String (ascii_of_nat 9) ")  || u ;  ") = (0, ("u")).
Proof. vm_compute; reflexivity. Qed.
Example random_195 : observe ("  (  t ;" ++ String (ascii_of_nat 9) "g" ++ String (ascii_of_nat 9) ")  && t" ++ String (ascii_of_nat 9) "||" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "u &&" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "u  ; u  ||  u|| u;  u;)  || f )  ") = (0, ("tguuuu")).
Proof. vm_compute; reflexivity. Qed.
Example random_196 : observe (" (" ++ String (ascii_of_nat 9) "t  )||" ++ String (ascii_of_nat 9) "g  &&  g  ;" ++ String (ascii_of_nat 9) "") = (2, ("tg")).
Proof. vm_compute; reflexivity. Qed.
Example random_197 : observe (" f  ||" ++ String (ascii_of_nat 9) "t ||  u  ") = (0, ("ft")).
Proof. vm_compute; reflexivity. Qed.
Example random_198 : observe ("" ++ String (ascii_of_nat 9) "u ||" ++ String (ascii_of_nat 9) "t  ; (" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) "|| g  )||f  ") = (1, ("ufgf")).
Proof. vm_compute; reflexivity. Qed.
Example random_199 : observe ("" ++ String (ascii_of_nat 9) "u  &&  u;" ++ String (ascii_of_nat 9) "u ;" ++ String (ascii_of_nat 9) "(" ++ String (ascii_of_nat 9) "( f" ++ String (ascii_of_nat 9) ";" ++ String (ascii_of_nat 9) "u &&" ++ String (ascii_of_nat 9) "f" ++ String (ascii_of_nat 9) ";t  &&" ++ String (ascii_of_nat 9) "u) &&( f;  t  )  && ( f  &&f;" ++ String (ascii_of_nat 9) "t" ++ String (ascii_of_nat 9) "&& f  ;" ++ String (ascii_of_nat 9) ")  )") = (1, ("uuufuftuftftf")).
Proof. vm_compute; reflexivity. Qed.
