#!/usr/bin/env python3
"""Directed validation of the bounded shell-text frontend against real Bash.

Two jobs, both driven by text_fixtures.json (the single source of texts):

  gen   -> writes Fixtures.v: for every accepted text an `Example` stating
           `parse_program "<text>" = Some (<ast>)` and
           `run test_env (<ast>) "" = (<status>, "<stdout>")`, and for every
           rejected text `parse_program "<text>" = None`. Coq (vm_compute)
           checks these; the .v file is regenerated, never hand-edited.
  random-> generates --count random texts of the fragment (--seed), runs each in
           bash, and writes RandomFixtures.v asserting that Coq's parse+run
           reproduces bash's actual status and stdout (bash is the oracle).
  bash  -> runs every accepted text through the host `bash -c` with the fixture
           functions t/u/f/g and compares exit status and stdout with the
           fixture; runs `bash -n` on rejected texts to record (informationally)
           whether Bash itself accepts the syntax we reject. Writes a JSON
           record outside the repository unless --out is given.

Passing finite tests does not prove the lexer or the grammar relation faithful
to Bash. They are directed evidence for a fixed fixture set (LC_ALL=C,
bash 5.x, host kernel); the checked object is Parse.v's soundness theorem.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import time

HERE = Path(__file__).resolve().parent
FIXTURES = HERE / 'text_fixtures.json'
PRELUDE = ('t(){ printf t; return 0; }; u(){ printf u; return 0; }; '
           'f(){ printf f; return 1; }; g(){ printf g; return 2; }; ')


def coq_string(text):
    out = []
    for ch in text:
        if ch == '"':
            out.append('""')
        elif ch == '\t':
            out.append('" ++ String (ascii_of_nat 9) "')
        elif ch == '\n':
            out.append('" ++ String (ascii_of_nat 10) "')
        elif ord(ch) > 126 or ord(ch) < 32:
            # Non-ASCII text is encoded byte-wise as UTF-8 code units.
            for b in ch.encode('utf-8'):
                out.append('" ++ String (ascii_of_nat %d) "' % b)
        else:
            out.append(ch)
    return '("' + ''.join(out) + '")'


def gen(fixtures):
    lines = ['(* GENERATED by validate_text.py gen from text_fixtures.json; do not edit. *)',
             'From Coq Require Import List Ascii String ZArith.',
             'Require Import Shell Parse.',
             'Import ListNotations ShellComposition ShellText.',
             'Local Open Scope string_scope.',
             'Local Open Scope Z_scope.',
             '']
    for i, case in enumerate(fixtures['accepted']):
        s = coq_string(case['text'])
        lines.append('Example accept_%d_parse : parse_program %s = Some (%s).'
                     % (i, s, case['ast']))
        lines.append('Proof. vm_compute; reflexivity. Qed.')
        lines.append('Example accept_%d_run : run test_env (%s) "" = (%d, %s).'
                     % (i, case['ast'], case['status'], coq_string(case['stdout'])))
        lines.append('Proof. vm_compute; reflexivity. Qed.')
    for i, case in enumerate(fixtures['rejected']):
        lines.append('Example reject_%d : parse_program %s = None.' % (i, coq_string(case['text'])))
        lines.append('Proof. vm_compute; reflexivity. Qed.')
    lines.append('')
    lines.append('(* Every accepted text therefore has a kernel-checked derivation: *)')
    lines.append('Example accept_0_derivation : exists toks, lex_string %s = Some toks /\\ body_derives toks (%s).'
                 % (coq_string(fixtures['accepted'][0]['text']), fixtures['accepted'][0]['ast']))
    lines.append('Proof. apply parse_program_sound. vm_compute; reflexivity. Qed.')
    lines.append('')
    return '\n'.join(lines)


def run_bash(script, seconds=5):
    env = {'PATH': os.environ.get('PATH', '/usr/bin:/bin'), 'LC_ALL': 'C'}
    started = time.monotonic()
    result = subprocess.run(['timeout', '--kill-after=2s', '%ds' % seconds, 'bash', '-c', script],
                            input=b'', capture_output=True, env=env, timeout=seconds + 4)
    return result, time.monotonic() - started


def bash(fixtures, out):
    bash_version = subprocess.check_output(['bash', '-c', 'echo "$BASH_VERSION"'], text=True).strip()
    records = []
    failures = 0
    for case in fixtures['accepted']:
        result, elapsed = run_bash(PRELUDE + case['text'])
        ok = result.returncode == case['status'] and result.stdout == case['stdout'].encode()
        failures += 0 if ok else 1
        records.append({'kind': 'accepted', 'text': case['text'], 'ast': case['ast'],
                        'expected': [case['status'], case['stdout']],
                        'bash': [result.returncode, result.stdout.decode('utf-8', 'replace')],
                        'bash_stderr': result.stderr.decode('utf-8', 'replace')[:200],
                        'agree': ok, 'seconds': round(elapsed, 4)})
    for case in fixtures['rejected']:
        result, elapsed = run_bash('bash -n -c ' + shell_quote(case['text']) + ' 2>/dev/null')
        records.append({'kind': 'rejected', 'text': case['text'], 'why': case['why'],
                        'bash_n_accepts': result.returncode == 0,
                        'seconds': round(elapsed, 4)})
    summary = {
        'fixtures_sha256': hashlib.sha256(FIXTURES.read_bytes()).hexdigest(),
        'bash_version': bash_version,
        'accepted_total': len(fixtures['accepted']),
        'accepted_disagreements': failures,
        'rejected_total': len(fixtures['rejected']),
        'rejected_but_bash_n_accepts': sum(1 for r in records if r['kind'] == 'rejected' and r['bash_n_accepts']),
        'scope': 'directed finite tests; not a parser correctness proof',
        'records': records,
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(summary, indent=1))
    print(json.dumps({k: v for k, v in summary.items() if k != 'records'}, indent=1))
    return failures


def random_text(rng, depth=0):
    """Random text of the fragment; blanks and parentheses are randomized."""
    names = ['t', 'u', 'f', 'g']
    def blank():
        return rng.choice(['', ' ', '  ', '\t'])
    def cmd(depth):
        if depth < 2 and rng.random() < 0.25:
            inner = lst(depth + 1)
            if rng.random() < 0.3:
                inner += blank() + ';'
            return '(' + blank() + inner + blank() + ')'
        return rng.choice(names)
    def andor(depth):
        text = cmd(depth)
        for _ in range(rng.choice([0, 0, 1, 1, 2, 3])):
            text += blank() + rng.choice(['&&', '||']) + blank() + cmd(depth)
        return text
    def lst(depth):
        text = andor(depth)
        for _ in range(rng.choice([0, 0, 1, 2])):
            text += blank() + ';' + blank() + andor(depth)
        return text
    text = lst(depth)
    if rng.random() < 0.2:
        text += blank() + ';'
    return blank() + text + blank()


def random_mode(count, seed, out):
    """Bash is the oracle: RandomFixtures.v asserts that parse+run reproduces bash's
    actual status/stdout for each random text (no Python evaluator is involved)."""
    import random
    rng = random.Random(seed)
    texts = []
    seen = set()
    while len(texts) < count:
        text = random_text(rng)
        if text in seen or '((' in text:
            # adjacent "((" is Bash arithmetic, outside the fragment (rejected by design)
            continue
        seen.add(text)
        texts.append(text)
    records = []
    lines = ['(* GENERATED by validate_text.py random --count %d --seed %d; bash %s is the oracle. *)' % (count, seed, '%s'),
             'From Coq Require Import List Ascii String ZArith.',
             'Require Import Shell Parse.',
             'Import ListNotations ShellComposition ShellText.',
             'Local Open Scope string_scope.',
             'Local Open Scope Z_scope.',
             'Definition observe (text : string) : Z * string :=',
             '  match parse_program text with',
             '  | Some c => run test_env c ""',
             '  | None => (-1, "")',
             '  end.',
             '']
    bash_version = subprocess.check_output(['bash', '-c', 'echo "$BASH_VERSION"'], text=True).strip()
    lines[0] = lines[0] % bash_version
    for i, text in enumerate(texts):
        result, elapsed = run_bash(PRELUDE + text)
        stdout = result.stdout.decode('ascii')
        records.append({'text': text, 'bash_status': result.returncode, 'bash_stdout': stdout,
                        'seconds': round(elapsed, 4)})
        lines.append('Example random_%d : observe %s = (%d, %s).' % (i, coq_string(text), result.returncode, coq_string(stdout)))
        lines.append('Proof. vm_compute; reflexivity. Qed.')
    (HERE / 'RandomFixtures.v').write_text('\n'.join(lines) + '\n')
    summary = {'seed': seed, 'count': len(texts), 'bash_version': bash_version,
               'scope': 'random texts of the fragment; bash status/stdout are the expected values that Coq must reproduce; finite evidence only',
               'records': records}
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(summary, indent=1))
    print('wrote', HERE / 'RandomFixtures.v', 'and', out, 'count', len(texts))
    return 0


def shell_quote(text):
    return "'" + text.replace("'", "'\\''") + "'"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('mode', choices=['gen', 'bash', 'random'])
    ap.add_argument('--count', type=int, default=200)
    ap.add_argument('--seed', type=int, default=1)
    ap.add_argument('--out', type=Path,
                    default=Path.home() / '.cache/bash-spec-pilot/phase5-shell-bridge/bash_validation.json')
    args = ap.parse_args()
    fixtures = json.loads(FIXTURES.read_text())
    if args.mode == 'random':
        return random_mode(args.count, args.seed,
                           args.out.expanduser().parent / 'random_validation.json')
    if args.mode == 'gen':
        (HERE / 'Fixtures.v').write_text(gen(fixtures))
        print('wrote', HERE / 'Fixtures.v')
        return 0
    return 1 if bash(fixtures, args.out.expanduser()) else 0


if __name__ == '__main__':
    sys.exit(main())
