#!/usr/bin/env python3
"""Emit coq/BytesOracle.v: the pinned interpreter's curated observations as Coq Examples
over the checked relay evaluator (phase5/relay/Evaluator.v, RelayEvaluator.eval, proved
sound/complete w.r.t. RelayReach.outcome).

Each positive Example states that eval on the same initial world (bytes, read and write
schedules) halts with exactly the status / pending / delivered / unread / call counts the
OCaml run printed; Coq checks it by vm_compute + reflexivity. `relay_seq_relay` chains two
evaluations on the final world (pending of the first is the shell ledger). Mutant records
that terminated normally with different values become `<>` Examples. If any OCaml value
were wrong, coqc would fail. Finite observations only: no statement about the OCaml code.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
INTERP = HERE / 'results' / 'interp'


def zlist(xs):
    return '[' + '; '.join(str(x) for x in xs) + ']'


def bytelist(hexs):
    bs = bytes.fromhex(hexs)
    return '(map Byte.repr ' + zlist(bs) + ')' if bs else '[]'


def zsched(xs):
    return '[' + '; '.join(f'({x})' if x < 0 else str(x) for x in xs) + ']'


def world(rec):
    return f"(World {bytelist(rec['input_hex'])} [] {zsched(rec['reads'])} {zsched(rec['writes'])} 0%nat 0%nat)"


def result(rec):
    a = rec['attrs']
    return (f"Some ({rec['rc']}, {bytelist(a['lost']['hex'])}, {bytelist(a['delivered']['hex'])}, "
            f"{bytelist(a['input']['hex'])}, {a['read_calls']}%nat, {a['write_calls']}%nat)")


def ident(s):
    return ''.join(c if c.isalnum() else '_' for c in s)


def runs(path):
    return [json.loads(l) for l in path.read_text().splitlines() if l.strip() and json.loads(l)['mode'] == 'run']


def main():
    out = ['(* GENERATED by make_coq_oracle.py from the pinned-interpreter observations in',
           '   results/interp/ (calculus-bytes worker, 2026-09-07). Do not edit by hand. *)',
           'From Coq Require Import List ZArith.',
           'From compcert Require Import Integers.',
           'Require Import Protocol Reach Evaluator.',
           'Import ListNotations RelayProtocol RelayReach RelayEvaluator.',
           'Local Open Scope Z_scope.',
           '',
           '(* status, pending (= shell ledger `lost`), delivered, unread, read calls, write calls *)',
           'Definition observe (w : world) :=',
           '  match eval (fuel w) (Ready, w) with',
           '  | Some (Halt st pend, fin) =>',
           '      Some (st, pend, delivered fin, unread fin, read_calls fin, write_calls fin)',
           '  | _ => None',
           '  end.',
           '',
           '(* relay ; relay : the second invocation starts from the final world of the first;',
           '   both pendings are discarded into the ledger, counters accumulate. *)',
           'Definition observe2 (w : world) :=',
           '  match eval (fuel w) (Ready, w) with',
           '  | Some (Halt _ pend1, fin1) =>',
           '      match eval (fuel fin1) (Ready, fin1) with',
           '      | Some (Halt st2 pend2, fin2) =>',
           '          Some (st2, pend1 ++ pend2, delivered fin2, unread fin2, read_calls fin2, write_calls fin2)',
           '      | _ => None',
           '      end',
           '  | _ => None',
           '  end.',
           '',
           '(* Soundness of the oracle itself (checked in Evaluator.v): eval_sound / eval_total. *)',
           'Check eval_sound.',
           'Check eval_total.',
           '']
    n_pos = 0
    for rec in runs(INTERP / 'curated_relay.jsonl'):
        assert rec['outcome'] == 'continue', rec['name']
        out.append(f"Example relay_{ident(rec['name'])} : observe {world(rec)} = {result(rec)}.")
        out.append('Proof. vm_compute. reflexivity. Qed.')
        n_pos += 1
    for rec in runs(INTERP / 'curated_relay_caught.jsonl'):
        assert rec['outcome'] == 'continue', rec['name']
        out.append(f"Example caught_{ident(rec['name'])} : observe {world(rec)} = {result(rec)}.")
        out.append('Proof. vm_compute. reflexivity. Qed.')
        n_pos += 1
    for rec in runs(INTERP / 'curated_relay_seq_relay.jsonl'):
        assert rec['outcome'] == 'continue', rec['name']
        out.append(f"Example seq_{ident(rec['name'])} : observe2 {world(rec)} = {result(rec)}.")
        out.append('Proof. vm_compute. reflexivity. Qed.')
        n_pos += 1
    n_neg = 0
    for m in ['mut_wrong_offset', 'mut_status_swap', 'mut_zero_write_retry']:
        ref = {r['name']: r for r in runs(INTERP / 'curated_relay.jsonl')}
        for rec in runs(INTERP / f'{m}_relay.jsonl'):
            if rec['outcome'] == 'continue' and result(rec) != result(ref[rec['name']]):
                out.append(f"Example {m}_{ident(rec['name'])} : observe {world(rec)} <> {result(rec)}.")
                out.append('Proof. vm_compute. discriminate. Qed.')
                n_neg += 1
    out.append('')
    out.append(f'(* {n_pos} positive observations, {n_neg} mutant observations. *)')
    (HERE / 'coq' / 'BytesOracle.v').write_text('\n'.join(out) + '\n')
    names = [l.split()[1] for l in out if l.startswith('Example ')]
    audit = ['(* GENERATED: Print Assumptions for every Example of BytesOracle.v *)',
             'Require Import BytesOracle.'] + [f'Print Assumptions {n}.' for n in names]
    (HERE / 'coq' / 'BytesOracleAudit.v').write_text('\n'.join(audit) + '\n')
    print(f'positive={n_pos} negative={n_neg}')


if __name__ == '__main__':
    main()
