/-
  GENERATED by calculus-correspondence/spec_ast_export/sexp_to_lean.py — do not edit.
  Source: the pinned frontend's parsed AST of `fixtures/byte_relay_exec.sc`, printed by
  `print_ast.exe` (calculus-correspondence/spec_ast_export/print_ast.ml, built in a private
  staging tree of the shared phase5-vst container; receipts in calculus-correspondence-75).
    raw export  : byte_relay_exec.ast.sexp  sha256 3f687ca1d1f8294266fac10194252059275b87e8eaf4b89c83fe84be8a67f2f4
    generator   : sexp_to_lean.py  sha256 cbb13c97875a1da1e99a6d964ee561b3e48a8b0ab7ceb3eb7ce4169348454082
  Every node of the raw export was in the supported fragment (the generator aborts otherwise).
-/
import CalculusLowering
open CalculusNested CalculusBody CalculusRelayOuter

namespace CalculusLowering

section ExportedProgram
open SExpr SStmt

/-- The machine-produced spec AST of `fixtures/byte_relay_exec.sc` (declarations in file order),
    translated node-for-node from the raw S-expression export. -/
def exportedSpec : List Decl :=
  [ .typeAlias "byte" .uint8,
    .attribute "input" (.list .uint8),
    .attribute "delivered" (.list .uint8),
    .attribute "lost" (.list .uint8),
    .attribute "reads" (.list .sint64),
    .attribute "writes" (.list .sint64),
    .attribute "read_calls" .sint64,
    .attribute "write_calls" .sint64,
    .element "block" [.sint64],
    .attribute "cap" .uint64,
    .attribute "len" .uint64,
    .attribute "bytes" (.list .uint8),
    .uninterp "length" [(.list .uint8)] .uint64,
    .uninterp "take" [(.list .uint8), .uint64] (.list .uint8),
    .uninterp "drop" [(.list .uint8), .uint64] (.list .uint8),
    .uninterp "slice" [(.list .uint8), .uint64, .uint64] (.list .uint8),
    .uninterp "append" [(.list .uint8), (.list .uint8)] (.list .uint8),
    .uninterp "empty" [] (.list .uint8),
    .uninterp "single" [.uint8] (.list .uint8),
    .uninterp "head_or" [(.list .sint64), .sint64] .sint64,
    .uninterp "tail" [(.list .sint64)] (.list .sint64),
    .uninterp "min" [.sint64, .sint64] .sint64,
    .uninterp "max" [.sint64, .sint64] .sint64,
    .exception "ReadError" [.sint64],
    .function "read_block" [("b", .stateRef)] .sint64
      [(letS "q" none (call "head_or" [(var "reads"), (field (var "b") "cap")])), (assign (var "reads") (call "tail" [(var "reads")])), (assign (var "read_calls") (binop .add (var "read_calls") (intLit 1))), (ifS (binop .lt (var "q") (intLit 0)) [(ret (neg (intLit 1)))] []), (letS "k" none (call "min" [(call "max" [(intLit 1), (var "q")]), (call "min" [(field (var "b") "cap"), (call "length" [(var "input")])])])), (assign (field (var "b") "bytes") (call "take" [(var "input"), (var "k")])), (assign (field (var "b") "len") (var "k")), (assign (var "input") (call "drop" [(var "input"), (var "k")])), (ret (var "k"))],
    .function "write_block" [("b", .stateRef), ("off", .uint64), ("n", .uint64)] .sint64
      [(assert (binop .le (var "off") (var "n"))), (assert (binop .le (var "n") (field (var "b") "len"))), (letS "l" none (field (var "b") "len")), (assert (binop .le (var "l") (field (var "b") "cap"))), (letS "req" none (call "slice" [(field (var "b") "bytes"), (var "off"), (var "n")])), (letS "q" none (call "head_or" [(var "writes"), (call "length" [(var "req")])])), (assign (var "writes") (call "tail" [(var "writes")])), (assign (var "write_calls") (binop .add (var "write_calls") (intLit 1))), (ifS (binop .lt (var "q") (intLit 0)) [(ret (neg (intLit 1)))] []), (letS "k" none (call "min" [(var "q"), (call "length" [(var "req")])])), (assign (var "delivered") (call "append" [(var "delivered"), (call "take" [(var "req"), (var "k")])])), (ret (var "k"))],
    .function "relay" [] .sint64
      [(clear (call "block" [(intLit 0)])), (touch (call "block" [(intLit 0)])), (letS "b" none (call "block" [(intLit 0)])), (assign (field (var "b") "cap") (intLit 32)), (assign (field (var "b") "len") (intLit 0)), (assign (field (var "b") "bytes") (call "empty" [])), (whileS (boolLit true) [(letS "r" none (call "read_block" [(var "b")])), (ifS (binop .lt (var "r") (intLit 0)) [(ret (intLit 1))] []), (ifS (binop .eq (var "r") (intLit 0)) [(ret (intLit 0))] []), (letS "off" none (intLit 0)), (whileS (binop .lt (var "off") (var "r")) [(letS "w" none (call "write_block" [(var "b"), (var "off"), (var "r")])), (ifS (binop .le (var "w") (intLit 0)) [(assign (var "lost") (call "append" [(var "lost"), (call "slice" [(field (var "b") "bytes"), (var "off"), (var "r")])])), (ret (intLit 2))] []), (assign (var "off") (binop .add (var "off") (var "w")))])])],
    .function "relay_raising" [] .sint64
      [(clear (call "block" [(intLit 0)])), (touch (call "block" [(intLit 0)])), (letS "b" none (call "block" [(intLit 0)])), (assign (field (var "b") "cap") (intLit 32)), (assign (field (var "b") "len") (intLit 0)), (assign (field (var "b") "bytes") (call "empty" [])), (whileS (boolLit true) [(letS "r" none (call "read_block" [(var "b")])), (ifS (binop .lt (var "r") (intLit 0)) [(raise "ReadError" [(var "r")])] []), (ifS (binop .eq (var "r") (intLit 0)) [(ret (intLit 0))] []), (letS "off" none (intLit 0)), (whileS (binop .lt (var "off") (var "r")) [(letS "w" none (call "write_block" [(var "b"), (var "off"), (var "r")])), (ifS (binop .le (var "w") (intLit 0)) [(assign (var "lost") (call "append" [(var "lost"), (call "slice" [(field (var "b") "bytes"), (var "off"), (var "r")])])), (ret (intLit 2))] []), (assign (var "off") (binop .add (var "off") (var "w")))])])],
    .function "relay_caught" [] .sint64
      [(tryCatch [(letS "s" none (call "relay_raising" [])), (ret (var "s"))] (some ("ReadError", ["code"], [(ret (intLit 1))])) [])],
    .function "mark" [] .sint64
      [(assign (var "delivered") (call "append" [(var "delivered"), (call "single" [(intLit 33)])])), (ret (intLit 0))],
    .function "relay_seq_relay" [] .sint64
      [(letS "a" none (call "relay" [])), (letS "c" none (call "relay" [])), (ret (var "c"))],
    .function "relay_and_mark" [] .sint64
      [(letS "rc" none (call "relay" [])), (ifS (binop .eq (var "rc") (intLit 0)) [(letS "m" none (call "mark" [])), (ret (var "m"))] []), (ret (var "rc"))],
    .function "relay_or_mark" [] .sint64
      [(letS "rc" none (call "relay" [])), (ifS (binop .eq (var "rc") (intLit 0)) [(ret (var "rc"))] []), (letS "m" none (call "mark" [])), (ret (var "m"))] ]

end ExportedProgram

/-- The machine-produced AST is EXACTLY the hand encoding used by `lowering_checked`: both are
    closed constructor terms, so the kernel decides the equality by definitional unfolding
    (`rfl`). `SExpr`/`SStmt` are nested inductives (`List SExpr` fields) for which Lean 4.31's
    `DecidableEq` deriving handler does not apply, so `decide` is not used here. -/
theorem exportedSpec_eq_hand : exportedSpec = byteRelayExecSpec := by
  rfl

/-- Composition: the Lean lowering of the MACHINE-PRODUCED spec AST is the nine exported bodies.
    This is a checked relation among (i) the pinned parser's own AST export, (ii) the Lean
    re-implementation of `lower.ml`, and (iii) the exported calculus; it is not a proof about the
    OCaml text of `lower.ml` or `interp.ml`. -/
theorem exported_lowers :
    lowerProgram exportedSpec = some
      [("read_block", readBlockBody), ("write_block", writeBlockBody), ("relay", relayBody),
       ("relay_raising", relayRaisingBody), ("relay_caught", relayCaughtBody), ("mark", markBody),
       ("relay_seq_relay", relaySeqRelayBody), ("relay_and_mark", relayAndMarkBody),
       ("relay_or_mark", relayOrMarkBody)] := by
  rw [exportedSpec_eq_hand]; exact lowering_checked

end CalculusLowering
