- name: Benchmark candidate
  hosts: all
  gather_facts: false
  tasks:
  - ansible.builtin.cron:
      name: astro cleanup
      minute: '0'
      hour: '15'
      user: root
      job: /usr/bin/true
